<a href="https://colab.research.google.com/github/jahid-dev/-Thesis-Data-Driven-Student-Behavior-Modeling-and-Dropout-Prediction-Using-Advanced-ML-Techniques/blob/main/01_UPV_Data_Audit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#SECTION 1: Environment Setup

In [ ]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)

print("Libraries imported successfully.")

Libraries imported successfully.

# SECTION 2: Google Drive & Project Paths

In [ ]:
#Mount Google Drive
from google.colab import drive

drive.mount("/content/drive")

In [ ]:
#Define Project Directories
BASE_DIR = Path(
    "/content/drive/MyDrive/Thesis Fall 2025 (DG1)/Code Implementation/Final"
)

DATA_DIR = BASE_DIR / "Datasets"

UPV_DIR = DATA_DIR / "UPV"
UCI_DIR = DATA_DIR / "UCI"
OULAD_DIR = DATA_DIR / "OULAD"

NOTEBOOK_DIR = BASE_DIR / "Notebooks"
RESULT_DIR = BASE_DIR / "Results"

print("BASE:", BASE_DIR.exists())
print("Datasets:", DATA_DIR.exists())
print("UPV:", UPV_DIR.exists())
print("UCI:", UCI_DIR.exists())
print("OULAD:", OULAD_DIR.exists())
print("Notebooks:", NOTEBOOK_DIR.exists())
print("Results:", RESULT_DIR.exists())

BASE: True
Datasets: True
UPV: True
UCI: True
OULAD: True
Notebooks: True
Results: True

# SECTION 3: Locate UPV Files

In [ ]:
#List UPV Files
print("UPV dataset files:\n")

upv_files = sorted(UPV_DIR.glob("*.csv"))

for file in upv_files:
    size_mb = file.stat().st_size / (1024 ** 2)
    print(f"{file.name} → {size_mb:.2f} MB")

print(f"\nTotal CSV files: {len(upv_files)}")

UPV dataset files:

dataset_2018_hash.csv → 74.15 MB
dataset_2021_hash.csv → 85.11 MB
dataset_2022_hash.csv → 87.44 MB

Total CSV files: 3

# SECTION 4: Load Datasets

In [ ]:
#Load 2018
df_2018 = pd.read_csv(
    UPV_DIR / "dataset_2018_hash.csv",
    sep=";",
    decimal=","
)

print("2018 dataset loaded.")
print("Shape:", df_2018.shape)

2018 dataset loaded.
Shape: (152446, 178)

In [ ]:
#Load 2021
df_2021 = pd.read_csv(
    UPV_DIR / "dataset_2021_hash.csv",
    sep=";",
    decimal=","
)

print("2021 dataset loaded.")
print("Shape:", df_2021.shape)

2021 dataset loaded.
Shape: (153120, 178)

In [ ]:
#Load 2022
df_2022 = pd.read_csv(
    UPV_DIR / "dataset_2022_hash.csv",
    sep=";",
    decimal=","
)

print("2022 dataset loaded.")
print("Shape:", df_2022.shape)

2022 dataset loaded.
Shape: (159173, 169)

#SECTION 5: Dataset Overview

In [ ]:
#Dataset Summary
dataset_summary = pd.DataFrame({
    "Year": [2018, 2021, 2022],

    "Records": [
        len(df_2018),
        len(df_2021),
        len(df_2022)
    ],

    "Columns": [
        df_2018.shape[1],
        df_2021.shape[1],
        df_2022.shape[1]
    ],

    "Unique_Students": [
        df_2018["dni_hash"].nunique(),
        df_2021["dni_hash"].nunique(),
        df_2022["dni_hash"].nunique()
    ]
})

display(dataset_summary)

   Year  Records  Columns  Unique_Students
0  2018   152446      178            20233
1  2021   153120      178            20264
2  2022   159173      169            20427

In [ ]:
#Total Records
total_records = (
    len(df_2018)
    + len(df_2021)
    + len(df_2022)
)

print(f"Total records across all years: {total_records:,}")

Total records across all years: 464,739

#SECTION 6: Data Types & Structure

In [ ]:
df_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152446 entries, 0 to 152445
Columns: 178 entries, dni_hash to n_resource_days_2019_8
dtypes: float64(158), int64(7), object(13)
memory usage: 207.0+ MB

In [ ]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153120 entries, 0 to 153119
Columns: 178 entries, dni_hash to n_resource_days_2022_8
dtypes: float64(158), int64(7), object(13)
memory usage: 207.9+ MB

In [ ]:
df_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159173 entries, 0 to 159172
Columns: 169 entries, dni_hash to n_resource_days_2023_7
dtypes: float64(149), int64(7), object(13)
memory usage: 205.2+ MB

In [ ]:
display(df_2018.head())

,dni_hash,tit_hash,asi_hash,anyo_ingreso,tipo_ingreso,nota10_hash,nota14_hash,campus_hash,estudios_p_hash,estudios_m_hash,dedicacion,desplazado_hash,abandono_hash,preferencia_seleccion,baja_fecha,caca,grupos_por_tipocredito_hash,matricula_activa,nota_asig_hash,fecha_datos,curso_mas_bajo,curso_mas_alto,cred_mat1,cred_mat2,cred_mat3,cred_mat4,cred_mat5,cred_mat6,cred_sup_normal,cred_sup_espec,cred_sup,cred_mat_normal,cred_mat_movilidad,cred_ptes_acta,cred_mat_practicas,cred_mat_sem_a,cred_mat_sem_b,cred_mat_anu,cred_mat_total,cred_sup_sem_a,cred_sup_sem_b,cred_sup_anu,cred_sup_total,rendimiento_cuat_a,rendimiento_cuat_b,rendimiento_total,exento_npp,anyo_inicio_estudios,es_retitulado,es_adaptado,cred_sup_1o,cred_sup_2o,cred_sup_3o,cred_sup_4o,cred_sup_5o,cred_sup_6o,practicas,actividades,ajuste,cred_sup_tit,cred_pend_sup_tit,impagado_curso_mat,asig1,pract1,activ1,total1,ajuste1,rend_total_ultimo,rend_total_penultimo,rend_total_antepenultimo,pft_events_2018_9,pft_days_logged_2018_9,pft_visits_2018_9,pft_assignment_submissions_2018_9,pft_test_submissions_2018_9,pft_total_minutes_2018_9,n_wifi_days_2018_9,resource_events_2018_9,n_resource_days_2018_9,pft_events_2018_10,pft_days_logged_2018_10,pft_visits_2018_10,pft_assignment_submissions_2018_10,pft_test_submissions_2018_10,pft_total_minutes_2018_10,n_wifi_days_2018_10,resource_events_2018_10,n_resource_days_2018_10,pft_events_2018_11,pft_days_logged_2018_11,pft_visits_2018_11,pft_assignment_submissions_2018_11,pft_test_submissions_2018_11,pft_total_minutes_2018_11,n_wifi_days_2018_11,resource_events_2018_11,n_resource_days_2018_11,pft_events_2018_12,pft_days_logged_2018_12,pft_visits_2018_12,pft_assignment_submissions_2018_12,pft_test_submissions_2018_12,pft_total_minutes_2018_12,n_wifi_days_2018_12,resource_events_2018_12,n_resource_days_2018_12,pft_events_2019_1,pft_days_logged_2019_1,pft_visits_2019_1,pft_assignment_submissions_2019_1,pft_test_submissions_2019_1,pft_total_minutes_2019_1,n_wifi_days_2019_1,resource_events_2019_1,n_resource_days_2019_1,pft_events_2019_2,pft_days_logged_2019_2,pft_visits_2019_2,pft_assignment_submissions_2019_2,pft_test_submissions_2019_2,pft_total_minutes_2019_2,n_wifi_days_2019_2,resource_events_2019_2,n_resource_days_2019_2,pft_events_2019_3,pft_days_logged_2019_3,pft_visits_2019_3,pft_assignment_submissions_2019_3,pft_test_submissions_2019_3,pft_total_minutes_2019_3,n_wifi_days_2019_3,resource_events_2019_3,n_resource_days_2019_3,pft_events_2019_4,pft_days_logged_2019_4,pft_visits_2019_4,pft_assignment_submissions_2019_4,pft_test_submissions_2019_4,pft_total_minutes_2019_4,n_wifi_days_2019_4,resource_events_2019_4,n_resource_days_2019_4,pft_events_2019_5,pft_days_logged_2019_5,pft_visits_2019_5,pft_assignment_submissions_2019_5,pft_test_submissions_2019_5,pft_total_minutes_2019_5,n_wifi_days_2019_5,resource_events_2019_5,n_resource_days_2019_5,pft_events_2019_6,pft_days_logged_2019_6,pft_visits_2019_6,pft_assignment_submissions_2019_6,pft_test_submissions_2019_6,pft_total_minutes_2019_6,n_wifi_days_2019_6,resource_events_2019_6,n_resource_days_2019_6,pft_events_2019_7,pft_days_logged_2019_7,pft_visits_2019_7,pft_assignment_submissions_2019_7,pft_test_submissions_2019_7,pft_total_minutes_2019_7,n_wifi_days_2019_7,resource_events_2019_7,n_resource_days_2019_7,pft_events_2019_8,pft_days_logged_2019_8,pft_visits_2019_8,pft_assignment_submissions_2019_8,pft_test_submissions_2019_8,pft_total_minutes_2019_8,n_wifi_days_2019_8,resource_events_2019_8,n_resource_days_2019_8
0,922787046182,1d0ebea552eb,024e9489dcc6,2013.0,NAP,7.541,10.548,6781b441c78d2643,T,F,TC,A,B,1.0,NaN,2018,5f5c45acdb805025,0.0,5.9,2023-06-28 16:04:41,3,4,0.0,0.0,30.0,19.5,0.0,0,19.5,0.0,19.5,49.5,0.0,0.0,0.0,34.5,15.0,0.0,49.5,15.0,4.5,0.0,19.5,NaN,NaN,NaN,NaN,2013,NaN,NaN,60.0,60.0,39.0,15.0,0.0,0,12.5,1.0,NaN,240.0,0.0,NaN,19.5,NaN,NaN,NaN,0,41.463415,56.410256,51.282051,5.0,NaN,NaN,NaN,NaN,45.070033,NaN,NaN,NaN,23.0,NaN,NaN,NaN,NaN,390.721517,NaN,11.0,4.0,3.0,NaN,NaN,NaN,NaN,46.240883,NaN,2.0,1.0,3.0,NaN,NaN,NaN,NaN,47.130483,NaN,1.0,1.0,55.0,NaN,NaN,NaN,NaN,939.066700,NaN,29.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,922787046182,1d0ebea552eb,007015a20672,2013.0,NAP,7.541,10.548,6781b441c78d2643,T,F,TC,A,B,1.0,NaN,2018,a2a4fff99a63c22b,0.0,2.7,2023-06-28 16:04:41,3,4,0.0,0.0,30.0,19.5,0.0,0,19.5,0.0,19.5,49.5,0.0,0.0,0.0,34.5,15.0,0.0,49.5,15.0,4.5,0.0,19.5,NaN,NaN,NaN,NaN,2013,NaN,NaN,60.0,60.0,39.0,15.0,0.0,0,12.5,1.0,NaN,240.0,0.0,NaN,19.5,NaN,NaN,NaN,0,41.463415,56.410256,51.282051,5.0,NaN,NaN,NaN,NaN,45.217583,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,136.462767,NaN,3.0,2.0,8.0,NaN,NaN,NaN,NaN,90.763967,NaN,3.0,2.0,4.0,NaN,NaN,NaN,NaN,77.589533,NaN,3.0,1.0,38.0,NaN,NaN,NaN,NaN,434.669483,NaN,20.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,45.191250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,922787046182,1d0ebea552eb,0bac83d121af,2013.0,NAP,7.541,10.548,6781b441c78d2643,T,F,TC,A,B,1.0,NaN,2018,5ee881f4a6d899d0,0.0,6.0,2023-06-28 16:04:41,3,4,0.0,0.0,30.0,19.5,0.0,0,19.5,0.0,19.5,49.5,0.0,0.0,0.0,34.5,15.0,0.0,49.5,15.0,4.5,0.0,19.5,NaN,NaN,NaN,NaN,2013,NaN,NaN,60.0,60.0,39.0,15.0,0.0,0,12.5,1.0,NaN,240.0,0.0,NaN,19.5,NaN,NaN,NaN,0,41.463415,56.410256,51.282051,14.0,NaN,NaN,NaN,NaN,182.849267,NaN,6.0,3.0,8.0,NaN,NaN,NaN,NaN,191.096467,NaN,2.0,2.0,27.0,NaN,NaN,NaN,NaN,303.244800,NaN,13.0,4.0,21.0,NaN,NaN,NaN,NaN,217.543117,NaN,11.0,1.0,69.0,NaN,NaN,NaN,NaN,731.726250,NaN,47.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,922787046182,1d0ebea552eb,88111a7f4d4f,2013.0,NAP,7.541,10.548,6781b441c78d2643,T,F,TC,A,B,1.0,NaN,2018,806af81a26823937,0.0,5.6,2023-06-28 16:04:41,3,4,0.0,0.0,30.0,19.5,0.0,0,19.5,0.0,19.5,49.5,0.0,0.0,0.0,34.5,15.0,0.0,49.5,15.0,4.5,0.0,19.5,NaN,NaN,NaN,NaN,2013,NaN,NaN,60.0,60.0,39.0,15.0,0.0,0,12.5,1.0,NaN,240.0,0.0,NaN,19.5,NaN,NaN,NaN,0,41.463415,56.410256,51.282051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,NaN,NaN,NaN,NaN,23.304117,NaN,5.0,2.0,3.0,NaN,NaN,NaN,NaN,39.412233,NaN,1.0,1.0,6.0,NaN,NaN,NaN,NaN,22.248450,NaN,3.0,1.0,10.0,NaN,NaN,NaN,NaN,162.157683,NaN,2.0,2.0,37.0,NaN,NaN,NaN,NaN,753.280033,NaN,12.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,922787046182,1d0ebea552eb,dc1cdc6ee450,2013.0,NAP,7.541,10.548,6781b441c78d2643,T,F,TC,A,B,1.0,NaN,2018,154e1483f9df59a4,0.0,4.1,2023-06-28 16:04:41,3,4,0.0,0.0,30.0,19.5,0.0,0,19.5,0.0,19.5,49.5,0.0,0.0,0.0,34.5,15.0,0.0,49.5,15.0,4.5,0.0,19.5,NaN,NaN,NaN,NaN,2013,NaN,NaN,60.0,60.0,39.0,15.0,0.0,0,12.5,1.0,NaN,240.0,0.0,NaN,19.5,NaN,NaN,NaN,0,41.463415,56.410256,51.282051,25.0,NaN,NaN,NaN,NaN,342.533883,NaN,5.0,1.0,31.0,NaN,NaN,NaN,NaN,457.710383,NaN,18.0,1.0,22.0,NaN,NaN,NaN,NaN,484.514417,NaN,9.0,3.0,19.0,NaN,NaN,NaN,NaN,522.879283,NaN,5.0,4.0,16.0,NaN,NaN,NaN,NaN,167.001100,NaN,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,46.014933,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
display(df_2018.sample(5, random_state=42))

,dni_hash,tit_hash,asi_hash,anyo_ingreso,tipo_ingreso,nota10_hash,nota14_hash,campus_hash,estudios_p_hash,estudios_m_hash,dedicacion,desplazado_hash,abandono_hash,preferencia_seleccion,baja_fecha,caca,grupos_por_tipocredito_hash,matricula_activa,nota_asig_hash,fecha_datos,curso_mas_bajo,curso_mas_alto,cred_mat1,cred_mat2,cred_mat3,cred_mat4,cred_mat5,cred_mat6,cred_sup_normal,cred_sup_espec,cred_sup,cred_mat_normal,cred_mat_movilidad,cred_ptes_acta,cred_mat_practicas,cred_mat_sem_a,cred_mat_sem_b,cred_mat_anu,cred_mat_total,cred_sup_sem_a,cred_sup_sem_b,cred_sup_anu,cred_sup_total,rendimiento_cuat_a,rendimiento_cuat_b,rendimiento_total,exento_npp,anyo_inicio_estudios,es_retitulado,es_adaptado,cred_sup_1o,cred_sup_2o,cred_sup_3o,cred_sup_4o,cred_sup_5o,cred_sup_6o,practicas,actividades,ajuste,cred_sup_tit,cred_pend_sup_tit,impagado_curso_mat,asig1,pract1,activ1,total1,ajuste1,rend_total_ultimo,rend_total_penultimo,rend_total_antepenultimo,pft_events_2018_9,pft_days_logged_2018_9,pft_visits_2018_9,pft_assignment_submissions_2018_9,pft_test_submissions_2018_9,pft_total_minutes_2018_9,n_wifi_days_2018_9,resource_events_2018_9,n_resource_days_2018_9,pft_events_2018_10,pft_days_logged_2018_10,pft_visits_2018_10,pft_assignment_submissions_2018_10,pft_test_submissions_2018_10,pft_total_minutes_2018_10,n_wifi_days_2018_10,resource_events_2018_10,n_resource_days_2018_10,pft_events_2018_11,pft_days_logged_2018_11,pft_visits_2018_11,pft_assignment_submissions_2018_11,pft_test_submissions_2018_11,pft_total_minutes_2018_11,n_wifi_days_2018_11,resource_events_2018_11,n_resource_days_2018_11,pft_events_2018_12,pft_days_logged_2018_12,pft_visits_2018_12,pft_assignment_submissions_2018_12,pft_test_submissions_2018_12,pft_total_minutes_2018_12,n_wifi_days_2018_12,resource_events_2018_12,n_resource_days_2018_12,pft_events_2019_1,pft_days_logged_2019_1,pft_visits_2019_1,pft_assignment_submissions_2019_1,pft_test_submissions_2019_1,pft_total_minutes_2019_1,n_wifi_days_2019_1,resource_events_2019_1,n_resource_days_2019_1,pft_events_2019_2,pft_days_logged_2019_2,pft_visits_2019_2,pft_assignment_submissions_2019_2,pft_test_submissions_2019_2,pft_total_minutes_2019_2,n_wifi_days_2019_2,resource_events_2019_2,n_resource_days_2019_2,pft_events_2019_3,pft_days_logged_2019_3,pft_visits_2019_3,pft_assignment_submissions_2019_3,pft_test_submissions_2019_3,pft_total_minutes_2019_3,n_wifi_days_2019_3,resource_events_2019_3,n_resource_days_2019_3,pft_events_2019_4,pft_days_logged_2019_4,pft_visits_2019_4,pft_assignment_submissions_2019_4,pft_test_submissions_2019_4,pft_total_minutes_2019_4,n_wifi_days_2019_4,resource_events_2019_4,n_resource_days_2019_4,pft_events_2019_5,pft_days_logged_2019_5,pft_visits_2019_5,pft_assignment_submissions_2019_5,pft_test_submissions_2019_5,pft_total_minutes_2019_5,n_wifi_days_2019_5,resource_events_2019_5,n_resource_days_2019_5,pft_events_2019_6,pft_days_logged_2019_6,pft_visits_2019_6,pft_assignment_submissions_2019_6,pft_test_submissions_2019_6,pft_total_minutes_2019_6,n_wifi_days_2019_6,resource_events_2019_6,n_resource_days_2019_6,pft_events_2019_7,pft_days_logged_2019_7,pft_visits_2019_7,pft_assignment_submissions_2019_7,pft_test_submissions_2019_7,pft_total_minutes_2019_7,n_wifi_days_2019_7,resource_events_2019_7,n_resource_days_2019_7,pft_events_2019_8,pft_days_logged_2019_8,pft_visits_2019_8,pft_assignment_submissions_2019_8,pft_test_submissions_2019_8,pft_total_minutes_2019_8,n_wifi_days_2019_8,resource_events_2019_8,n_resource_days_2019_8
109145,06abdceb6278,734d0759cdb4,3dff5ac730d4,2018.0,NAP,7.075,9.694,16a36e86f6fed5d4,F,F,TC,B,B,1.0,NaN,2018,b8ebd6577e874470,0.0,8.1,2023-06-28 16:04:41,1,1,60.0,0.0,0.0,0.0,0.0,0,60.0,0.0,60.0,60.0,0.0,0.0,0.0,18.0,24.0,18.0,60.0,18.0,24.0,18.0,60.0,NaN,NaN,NaN,NaN,2018,NaN,NaN,60.0,0.0,0.0,0.0,0.0,0,0.0,NaN,NaN,240.0,0.0,NaN,60.0,NaN,NaN,NaN,0,NaN,NaN,NaN,60.0,NaN,NaN,NaN,NaN,810.32525,NaN,28.0,7.0,72.0,NaN,NaN,NaN,NaN,1038.413417,NaN,39.0,11.0,76.0,NaN,NaN,NaN,NaN,1021.773450,NaN,41.0,14.0,16.0,NaN,NaN,NaN,NaN,318.686617,NaN,9.0,4.0,9.0,NaN,NaN,NaN,NaN,137.228467,NaN,5.0,2.0,1.0,NaN,NaN,NaN,NaN,47.160817,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,135.866667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,197.882067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113667,c533ce7b9bb0,3d3286f7cd19,f5dbfdb34618,2016.0,NAP,6.544,9.454,60f19cd67252161d,L,F,TC,A,B,3.0,NaN,2018,915c4d5f8e285518,0.0,6.1,2023-06-28 16:04:41,1,3,6.0,0.0,52.5,0.0,0.0,0,58.5,0.0,58.5,60.0,0.0,0.0,1.5,28.5,30.0,0.0,58.5,28.5,30.0,0.0,58.5,NaN,NaN,NaN,NaN,2016,NaN,NaN,66.0,60.0,52.5,0.0,0.0,0,12.0,NaN,NaN,240.0,0.0,NaN,58.5,NaN,NaN,NaN,0,100.000000,100.0,NaN,7.0,NaN,NaN,NaN,NaN,91.62400,NaN,NaN,NaN,38.0,NaN,NaN,NaN,NaN,439.741333,NaN,23.0,6.0,32.0,NaN,NaN,NaN,NaN,474.512000,NaN,10.0,4.0,18.0,NaN,NaN,NaN,NaN,409.796567,NaN,10.0,4.0,57.0,NaN,NaN,NaN,NaN,908.329950,NaN,31.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36991,2e39f743f592,1d0ebea552eb,5bc6f0850db9,2015.0,NAP,8.342,11.058,6781b441c78d2643,F,L,TC,A,B,1.0,NaN,2018,dbe8723002e8e935,0.0,6.8,2023-06-28 16:04:41,2,3,0.0,39.0,21.0,0.0,0.0,0,30.0,0.0,30.0,60.0,0.0,0.0,0.0,33.0,27.0,0.0,60.0,16.5,13.5,0.0,30.0,NaN,NaN,NaN,NaN,2015,NaN,NaN,60.0,51.0,0.0,0.0,0.0,0,0.0,NaN,NaN,240.0,0.0,NaN,30.0,NaN,NaN,NaN,0,56.410256,75.0,20.0,1.0,NaN,NaN,NaN,NaN,45.11810,NaN,NaN,NaN,31.0,NaN,NaN,NaN,NaN,693.499467,NaN,12.0,5.0,1.0,NaN,NaN,NaN,NaN,45.228833,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,189.052317,NaN,4.0,1.0,129.0,NaN,NaN,NaN,NaN,1808.331833,NaN,64.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28399,ded502518319,1d0ebea552eb,6422cb4858f1,2017.0,NAP,8.458,12.028,6781b441c78d2643,L,L,TC,A,B,1.0,NaN,2018,650056c80d687155,0.0,2.9,2023-06-28 16:04:41,2,2,0.0,60.0,0.0,0.0,0.0,0,42.0,0.0,42.0,60.0,0.0,0.0,0.0,31.5,28.5,0.0,60.0,27.0,15.0,0.0,42.0,NaN,NaN,NaN,NaN,2017,NaN,NaN,60.0,42.0,0.0,0.0,0.0,0,0.0,NaN,NaN,240.0,0.0,NaN,42.0,NaN,NaN,NaN,0,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,97.461450,NaN,2.0,1.0,31.0,NaN,NaN,NaN,NaN,551.618117,NaN,17.0,5.0,52.0,NaN,NaN,NaN,NaN,1039.717800,NaN,26.0,7.0,56.0,NaN,NaN,NaN,NaN,710.50295,NaN,33.0,5.0,114.0,NaN,NaN,NaN,NaN,1373.413000,NaN,60.0,8.0,75.0,NaN,NaN,NaN,NaN,1038.361517,NaN,38.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,48.817267,NaN,NaN,NaN
56778,57721fe26dbe,1d0ebea552eb,47a75f17bd50,NaN,NaN,NaN,NaN,6781b441c78d2643,L,L,TC,B,B,1.0,2019-07-15,2018,NaN,0.0,5.8,2023-06-28 16:04:41,1,1,60.0,60.0,60.0,51.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,121.5,109.5,0.0,231.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2018,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,0.0,NaN,9.0,0.0,240.0,1.0,0.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# SECTION 7: Column Consistency

> Add blockquote

> Add blockquote

> Add blockquote

> Add blockquote

> Add blockquote

In [ ]:
#Compare Column Counts
cols_2018 = set(df_2018.columns)
cols_2021 = set(df_2021.columns)
cols_2022 = set(df_2022.columns)

print("2018 columns:", len(cols_2018))
print("2021 columns:", len(cols_2021))
print("2022 columns:", len(cols_2022))

2018 columns: 178
2021 columns: 178
2022 columns: 169

In [ ]:
#Common Columns
common_columns = (
    cols_2018
    & cols_2021
    & cols_2022
)

print(
    "Common columns across all three years:",
    len(common_columns)
)

Common columns across all three years: 70

In [ ]:
#2018 vs 2022 Differences
print("Columns in 2018 but not in 2022:")
print(sorted(cols_2018 - cols_2022))

print("\nColumns in 2022 but not in 2018:")
print(sorted(cols_2022 - cols_2018))

Columns in 2018 but not in 2022:
['n_resource_days_2018_10', 'n_resource_days_2018_11', 'n_resource_days_2018_12', 'n_resource_days_2018_9', 'n_resource_days_2019_1', 'n_resource_days_2019_2', 'n_resource_days_2019_3', 'n_resource_days_2019_4', 'n_resource_days_2019_5', 'n_resource_days_2019_6', 'n_resource_days_2019_7', 'n_resource_days_2019_8', 'n_wifi_days_2018_10', 'n_wifi_days_2018_11', 'n_wifi_days_2018_12', 'n_wifi_days_2018_9', 'n_wifi_days_2019_1', 'n_wifi_days_2019_2', 'n_wifi_days_2019_3', 'n_wifi_days_2019_4', 'n_wifi_days_2019_5', 'n_wifi_days_2019_6', 'n_wifi_days_2019_7', 'n_wifi_days_2019_8', 'pft_assignment_submissions_2018_10', 'pft_assignment_submissions_2018_11', 'pft_assignment_submissions_2018_12', 'pft_assignment_submissions_2018_9', 'pft_assignment_submissions_2019_1', 'pft_assignment_submissions_2019_2', 'pft_assignment_submissions_2019_3', 'pft_assignment_submissions_2019_4', 'pft_assignment_submissions_2019_5', 'pft_assignment_submissions_2019_6', 'pft_assignment_submissions_2019_7', 'pft_assignment_submissions_2019_8', 'pft_days_logged_2018_10', 'pft_days_logged_2018_11', 'pft_days_logged_2018_12', 'pft_days_logged_2018_9', 'pft_days_logged_2019_1', 'pft_days_logged_2019_2', 'pft_days_logged_2019_3', 'pft_days_logged_2019_4', 'pft_days_logged_2019_5', 'pft_days_logged_2019_6', 'pft_days_logged_2019_7', 'pft_days_logged_2019_8', 'pft_events_2018_10', 'pft_events_2018_11', 'pft_events_2018_12', 'pft_events_2018_9', 'pft_events_2019_1', 'pft_events_2019_2', 'pft_events_2019_3', 'pft_events_2019_4', 'pft_events_2019_5', 'pft_events_2019_6', 'pft_events_2019_7', 'pft_events_2019_8', 'pft_test_submissions_2018_10', 'pft_test_submissions_2018_11', 'pft_test_submissions_2018_12', 'pft_test_submissions_2018_9', 'pft_test_submissions_2019_1', 'pft_test_submissions_2019_2', 'pft_test_submissions_2019_3', 'pft_test_submissions_2019_4', 'pft_test_submissions_2019_5', 'pft_test_submissions_2019_6', 'pft_test_submissions_2019_7', 'pft_test_submissions_2019_8', 'pft_total_minutes_2018_10', 'pft_total_minutes_2018_11', 'pft_total_minutes_2018_12', 'pft_total_minutes_2018_9', 'pft_total_minutes_2019_1', 'pft_total_minutes_2019_2', 'pft_total_minutes_2019_3', 'pft_total_minutes_2019_4', 'pft_total_minutes_2019_5', 'pft_total_minutes_2019_6', 'pft_total_minutes_2019_7', 'pft_total_minutes_2019_8', 'pft_visits_2018_10', 'pft_visits_2018_11', 'pft_visits_2018_12', 'pft_visits_2018_9', 'pft_visits_2019_1', 'pft_visits_2019_2', 'pft_visits_2019_3', 'pft_visits_2019_4', 'pft_visits_2019_5', 'pft_visits_2019_6', 'pft_visits_2019_7', 'pft_visits_2019_8', 'resource_events_2018_10', 'resource_events_2018_11', 'resource_events_2018_12', 'resource_events_2018_9', 'resource_events_2019_1', 'resource_events_2019_2', 'resource_events_2019_3', 'resource_events_2019_4', 'resource_events_2019_5', 'resource_events_2019_6', 'resource_events_2019_7', 'resource_events_2019_8']

Columns in 2022 but not in 2018:
['n_resource_days_2022_10', 'n_resource_days_2022_11', 'n_resource_days_2022_12', 'n_resource_days_2022_9', 'n_resource_days_2023_1', 'n_resource_days_2023_2', 'n_resource_days_2023_3', 'n_resource_days_2023_4', 'n_resource_days_2023_5', 'n_resource_days_2023_6', 'n_resource_days_2023_7', 'n_wifi_days_2022_10', 'n_wifi_days_2022_11', 'n_wifi_days_2022_12', 'n_wifi_days_2022_9', 'n_wifi_days_2023_1', 'n_wifi_days_2023_2', 'n_wifi_days_2023_3', 'n_wifi_days_2023_4', 'n_wifi_days_2023_5', 'n_wifi_days_2023_6', 'n_wifi_days_2023_7', 'pft_assignment_submissions_2022_10', 'pft_assignment_submissions_2022_11', 'pft_assignment_submissions_2022_12', 'pft_assignment_submissions_2022_9', 'pft_assignment_submissions_2023_1', 'pft_assignment_submissions_2023_2', 'pft_assignment_submissions_2023_3', 'pft_assignment_submissions_2023_4', 'pft_assignment_submissions_2023_5', 'pft_assignment_submissions_2023_6', 'pft_assignment_submissions_2023_7', 'pft_days_logged_2022_10', 'pft_days_logged_2022_11', 'pft_days_logged_2022_12', 'pft_days_logged_2022_9', 'pft_days_logged_2023_1', 'pft_days_logged_2023_2', 'pft_days_logged_2023_3', 'pft_days_logged_2023_4', 'pft_days_logged_2023_5', 'pft_days_logged_2023_6', 'pft_days_logged_2023_7', 'pft_events_2022_10', 'pft_events_2022_11', 'pft_events_2022_12', 'pft_events_2022_9', 'pft_events_2023_1', 'pft_events_2023_2', 'pft_events_2023_3', 'pft_events_2023_4', 'pft_events_2023_5', 'pft_events_2023_6', 'pft_events_2023_7', 'pft_test_submissions_2022_10', 'pft_test_submissions_2022_11', 'pft_test_submissions_2022_12', 'pft_test_submissions_2022_9', 'pft_test_submissions_2023_1', 'pft_test_submissions_2023_2', 'pft_test_submissions_2023_3', 'pft_test_submissions_2023_4', 'pft_test_submissions_2023_5', 'pft_test_submissions_2023_6', 'pft_test_submissions_2023_7', 'pft_total_minutes_2022_10', 'pft_total_minutes_2022_11', 'pft_total_minutes_2022_12', 'pft_total_minutes_2022_9', 'pft_total_minutes_2023_1', 'pft_total_minutes_2023_2', 'pft_total_minutes_2023_3', 'pft_total_minutes_2023_4', 'pft_total_minutes_2023_5', 'pft_total_minutes_2023_6', 'pft_total_minutes_2023_7', 'pft_visits_2022_10', 'pft_visits_2022_11', 'pft_visits_2022_12', 'pft_visits_2022_9', 'pft_visits_2023_1', 'pft_visits_2023_2', 'pft_visits_2023_3', 'pft_visits_2023_4', 'pft_visits_2023_5', 'pft_visits_2023_6', 'pft_visits_2023_7', 'resource_events_2022_10', 'resource_events_2022_11', 'resource_events_2022_12', 'resource_events_2022_9', 'resource_events_2023_1', 'resource_events_2023_2', 'resource_events_2023_3', 'resource_events_2023_4', 'resource_events_2023_5', 'resource_events_2023_6', 'resource_events_2023_7']

In [ ]:
#2021 vs 2022 Differences
print("Columns in 2021 but not in 2022:")
print(sorted(cols_2021 - cols_2022))

print("\nColumns in 2022 but not in 2021:")
print(sorted(cols_2022 - cols_2021))

Columns in 2021 but not in 2022:
['n_resource_days_2021_10', 'n_resource_days_2021_11', 'n_resource_days_2021_12', 'n_resource_days_2021_9', 'n_resource_days_2022_1', 'n_resource_days_2022_2', 'n_resource_days_2022_3', 'n_resource_days_2022_4', 'n_resource_days_2022_5', 'n_resource_days_2022_6', 'n_resource_days_2022_7', 'n_resource_days_2022_8', 'n_wifi_days_2021_10', 'n_wifi_days_2021_11', 'n_wifi_days_2021_12', 'n_wifi_days_2021_9', 'n_wifi_days_2022_1', 'n_wifi_days_2022_2', 'n_wifi_days_2022_3', 'n_wifi_days_2022_4', 'n_wifi_days_2022_5', 'n_wifi_days_2022_6', 'n_wifi_days_2022_7', 'n_wifi_days_2022_8', 'pft_assignment_submissions_2021_10', 'pft_assignment_submissions_2021_11', 'pft_assignment_submissions_2021_12', 'pft_assignment_submissions_2021_9', 'pft_assignment_submissions_2022_1', 'pft_assignment_submissions_2022_2', 'pft_assignment_submissions_2022_3', 'pft_assignment_submissions_2022_4', 'pft_assignment_submissions_2022_5', 'pft_assignment_submissions_2022_6', 'pft_assignment_submissions_2022_7', 'pft_assignment_submissions_2022_8', 'pft_days_logged_2021_10', 'pft_days_logged_2021_11', 'pft_days_logged_2021_12', 'pft_days_logged_2021_9', 'pft_days_logged_2022_1', 'pft_days_logged_2022_2', 'pft_days_logged_2022_3', 'pft_days_logged_2022_4', 'pft_days_logged_2022_5', 'pft_days_logged_2022_6', 'pft_days_logged_2022_7', 'pft_days_logged_2022_8', 'pft_events_2021_10', 'pft_events_2021_11', 'pft_events_2021_12', 'pft_events_2021_9', 'pft_events_2022_1', 'pft_events_2022_2', 'pft_events_2022_3', 'pft_events_2022_4', 'pft_events_2022_5', 'pft_events_2022_6', 'pft_events_2022_7', 'pft_events_2022_8', 'pft_test_submissions_2021_10', 'pft_test_submissions_2021_11', 'pft_test_submissions_2021_12', 'pft_test_submissions_2021_9', 'pft_test_submissions_2022_1', 'pft_test_submissions_2022_2', 'pft_test_submissions_2022_3', 'pft_test_submissions_2022_4', 'pft_test_submissions_2022_5', 'pft_test_submissions_2022_6', 'pft_test_submissions_2022_7', 'pft_test_submissions_2022_8', 'pft_total_minutes_2021_10', 'pft_total_minutes_2021_11', 'pft_total_minutes_2021_12', 'pft_total_minutes_2021_9', 'pft_total_minutes_2022_1', 'pft_total_minutes_2022_2', 'pft_total_minutes_2022_3', 'pft_total_minutes_2022_4', 'pft_total_minutes_2022_5', 'pft_total_minutes_2022_6', 'pft_total_minutes_2022_7', 'pft_total_minutes_2022_8', 'pft_visits_2021_10', 'pft_visits_2021_11', 'pft_visits_2021_12', 'pft_visits_2021_9', 'pft_visits_2022_1', 'pft_visits_2022_2', 'pft_visits_2022_3', 'pft_visits_2022_4', 'pft_visits_2022_5', 'pft_visits_2022_6', 'pft_visits_2022_7', 'pft_visits_2022_8', 'resource_events_2021_10', 'resource_events_2021_11', 'resource_events_2021_12', 'resource_events_2021_9', 'resource_events_2022_1', 'resource_events_2022_2', 'resource_events_2022_3', 'resource_events_2022_4', 'resource_events_2022_5', 'resource_events_2022_6', 'resource_events_2022_7', 'resource_events_2022_8']

Columns in 2022 but not in 2021:
['n_resource_days_2022_10', 'n_resource_days_2022_11', 'n_resource_days_2022_12', 'n_resource_days_2022_9', 'n_resource_days_2023_1', 'n_resource_days_2023_2', 'n_resource_days_2023_3', 'n_resource_days_2023_4', 'n_resource_days_2023_5', 'n_resource_days_2023_6', 'n_resource_days_2023_7', 'n_wifi_days_2022_10', 'n_wifi_days_2022_11', 'n_wifi_days_2022_12', 'n_wifi_days_2022_9', 'n_wifi_days_2023_1', 'n_wifi_days_2023_2', 'n_wifi_days_2023_3', 'n_wifi_days_2023_4', 'n_wifi_days_2023_5', 'n_wifi_days_2023_6', 'n_wifi_days_2023_7', 'pft_assignment_submissions_2022_10', 'pft_assignment_submissions_2022_11', 'pft_assignment_submissions_2022_12', 'pft_assignment_submissions_2022_9', 'pft_assignment_submissions_2023_1', 'pft_assignment_submissions_2023_2', 'pft_assignment_submissions_2023_3', 'pft_assignment_submissions_2023_4', 'pft_assignment_submissions_2023_5', 'pft_assignment_submissions_2023_6', 'pft_assignment_submissions_2023_7', 'pft_days_logged_2022_10', 'pft_days_logged_2022_11', 'pft_days_logged_2022_12', 'pft_days_logged_2022_9', 'pft_days_logged_2023_1', 'pft_days_logged_2023_2', 'pft_days_logged_2023_3', 'pft_days_logged_2023_4', 'pft_days_logged_2023_5', 'pft_days_logged_2023_6', 'pft_days_logged_2023_7', 'pft_events_2022_10', 'pft_events_2022_11', 'pft_events_2022_12', 'pft_events_2022_9', 'pft_events_2023_1', 'pft_events_2023_2', 'pft_events_2023_3', 'pft_events_2023_4', 'pft_events_2023_5', 'pft_events_2023_6', 'pft_events_2023_7', 'pft_test_submissions_2022_10', 'pft_test_submissions_2022_11', 'pft_test_submissions_2022_12', 'pft_test_submissions_2022_9', 'pft_test_submissions_2023_1', 'pft_test_submissions_2023_2', 'pft_test_submissions_2023_3', 'pft_test_submissions_2023_4', 'pft_test_submissions_2023_5', 'pft_test_submissions_2023_6', 'pft_test_submissions_2023_7', 'pft_total_minutes_2022_10', 'pft_total_minutes_2022_11', 'pft_total_minutes_2022_12', 'pft_total_minutes_2022_9', 'pft_total_minutes_2023_1', 'pft_total_minutes_2023_2', 'pft_total_minutes_2023_3', 'pft_total_minutes_2023_4', 'pft_total_minutes_2023_5', 'pft_total_minutes_2023_6', 'pft_total_minutes_2023_7', 'pft_visits_2022_10', 'pft_visits_2022_11', 'pft_visits_2022_12', 'pft_visits_2022_9', 'pft_visits_2023_1', 'pft_visits_2023_2', 'pft_visits_2023_3', 'pft_visits_2023_4', 'pft_visits_2023_5', 'pft_visits_2023_6', 'pft_visits_2023_7', 'resource_events_2022_10', 'resource_events_2022_11', 'resource_events_2022_12', 'resource_events_2022_9', 'resource_events_2023_1', 'resource_events_2023_2', 'resource_events_2023_3', 'resource_events_2023_4', 'resource_events_2023_5', 'resource_events_2023_6', 'resource_events_2023_7']

# SECTION 8: Temporal Feature Inventory

In [ ]:
#Identify Time-Based Behavioral Columns
behavior_prefixes = [
    "pft_events_",
    "pft_visits_",
    "pft_days_logged_",
    "pft_assignment_submissions_",
    "pft_test_submissions_",
    "pft_total_minutes_",
    "resource_events_",
    "n_resource_days_",
    "n_wifi_days_"
]

def get_behavior_columns(df):
    return [
        col
        for col in df.columns
        if any(col.startswith(prefix) for prefix in behavior_prefixes)
    ]

for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:
    cols = get_behavior_columns(df)

    print(f"{year}: {len(cols)} behavioral/time-based columns")

2018: 108 behavioral/time-based columns
2021: 108 behavioral/time-based columns
2022: 99 behavioral/time-based columns

In [ ]:
#Count by Behavioral Type
for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:

    print(f"\n===== {year} =====")

    for prefix in behavior_prefixes:
        count = sum(
            col.startswith(prefix)
            for col in df.columns
        )

        print(f"{prefix:<35} {count}")

===== 2018 =====
pft_events_                         12
pft_visits_                         12
pft_days_logged_                    12
pft_assignment_submissions_         12
pft_test_submissions_               12
pft_total_minutes_                  12
resource_events_                    12
n_resource_days_                    12
n_wifi_days_                        12

===== 2021 =====
pft_events_                         12
pft_visits_                         12
pft_days_logged_                    12
pft_assignment_submissions_         12
pft_test_submissions_               12
pft_total_minutes_                  12
resource_events_                    12
n_resource_days_                    12
n_wifi_days_                        12

===== 2022 =====
pft_events_                         11
pft_visits_                         11
pft_days_logged_                    11
pft_assignment_submissions_         11
pft_test_submissions_               11
pft_total_minutes_                  11
resource_events_                    11
n_resource_days_                    11
n_wifi_days_                        11

# SECTION 9: Temporal Window Analysis

In [ ]:
#Extract time windows
import re

def extract_time_windows(df):
    pattern = re.compile(r'_(\d{4})_(\d+)$')

    windows = set()

    for col in df.columns:
        match = pattern.search(col)
        if match:
            year = int(match.group(1))
            month = int(match.group(2))
            windows.add((year, month))

    return sorted(windows)


for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:
    windows = extract_time_windows(df)

    print(f"\n===== {year} =====")
    print("Number of time windows:", len(windows))
    print("Time windows:")
    print(windows)

===== 2018 =====
Number of time windows: 12
Time windows:
[(2018, 9), (2018, 10), (2018, 11), (2018, 12), (2019, 1), (2019, 2), (2019, 3), (2019, 4), (2019, 5), (2019, 6), (2019, 7), (2019, 8)]

===== 2021 =====
Number of time windows: 12
Time windows:
[(2021, 9), (2021, 10), (2021, 11), (2021, 12), (2022, 1), (2022, 2), (2022, 3), (2022, 4), (2022, 5), (2022, 6), (2022, 7), (2022, 8)]

===== 2022 =====
Number of time windows: 11
Time windows:
[(2022, 9), (2022, 10), (2022, 11), (2022, 12), (2023, 1), (2023, 2), (2023, 3), (2023, 4), (2023, 5), (2023, 6), (2023, 7)]

In [ ]:
for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:

    windows = extract_time_windows(df)

    print(f"\n{year}:")
    print(" → ".join(f"{y}-{m:02d}" for y, m in windows))

2018:
2018-09 → 2018-10 → 2018-11 → 2018-12 → 2019-01 → 2019-02 → 2019-03 → 2019-04 → 2019-05 → 2019-06 → 2019-07 → 2019-08

2021:
2021-09 → 2021-10 → 2021-11 → 2021-12 → 2022-01 → 2022-02 → 2022-03 → 2022-04 → 2022-05 → 2022-06 → 2022-07 → 2022-08

2022:
2022-09 → 2022-10 → 2022-11 → 2022-12 → 2023-01 → 2023-02 → 2023-03 → 2023-04 → 2023-05 → 2023-06 → 2023-07

# SECTION 10: Feature Group Summary

In [ ]:
feature_group_summary = {
    "PFT Events": "pft_events_",
    "PFT Visits": "pft_visits_",
    "PFT Days Logged": "pft_days_logged_",
    "PFT Assignment Submissions": "pft_assignment_submissions_",
    "PFT Test Submissions": "pft_test_submissions_",
    "PFT Total Minutes": "pft_total_minutes_",
    "Wi-Fi Active Days": "n_wifi_days_",
    "Resource Events": "resource_events_",
    "Resource Activity Days": "n_resource_days_"
}

for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:

    print(f"\n===== {year} =====")

    for name, prefix in feature_group_summary.items():
        count = sum(col.startswith(prefix) for col in df.columns)
        print(f"{name:<30} {count}")

===== 2018 =====
PFT Events                     12
PFT Visits                     12
PFT Days Logged                12
PFT Assignment Submissions     12
PFT Test Submissions           12
PFT Total Minutes              12
Wi-Fi Active Days              12
Resource Events                12
Resource Activity Days         12

===== 2021 =====
PFT Events                     12
PFT Visits                     12
PFT Days Logged                12
PFT Assignment Submissions     12
PFT Test Submissions           12
PFT Total Minutes              12
Wi-Fi Active Days              12
Resource Events                12
Resource Activity Days         12

===== 2022 =====
PFT Events                     11
PFT Visits                     11
PFT Days Logged                11
PFT Assignment Submissions     11
PFT Test Submissions           11
PFT Total Minutes              11
Wi-Fi Active Days              11
Resource Events                11
Resource Activity Days         11

#SECTION 10A: Feature Group Summary

In [ ]:

# SECTION 10A: FEATURE GROUP SUMMARY


# Feature groups are defined based on the observed UPV column
# names and temporal feature prefixes.

FEATURE_GROUP_RULES = {

    "Student Identity": [
        "dni_hash",
        "tit_hash",
        "asi_hash"
    ],

    "Admission Information": [
        "anyo_ingreso",
        "tipo_ingreso",
        "preferencia_seleccion",
        "campus_hash",
        "desplazado_hash"
    ],

    "Academic Background": [
        "estudios_p_hash",
        "estudios_m_hash",
        "dedicacion",
        "anyo_inicio_estudios",
        "es_retitulado",
        "es_adaptado"
    ],

    "Academic Performance": [
        "nota10_hash",
        "nota14_hash",
        "nota_asig_hash",
        "rendimiento_cuat_a",
        "rendimiento_cuat_b",
        "rendimiento_total",
        "rend_total_ultimo",
        "rend_total_penultimo",
        "rend_total_antepenultimo",
        "exento_npp"
    ],

    "Course Progress": [
        "curso_mas_bajo",
        "curso_mas_alto"
    ],

    "Credit Information": [
        "cred_mat1",
        "cred_mat2",
        "cred_mat3",
        "cred_mat4",
        "cred_mat5",
        "cred_mat6",
        "cred_sup_normal",
        "cred_sup_espec",
        "cred_sup",
        "cred_mat_normal",
        "cred_mat_movilidad",
        "cred_ptes_acta",
        "cred_mat_practicas",
        "cred_mat_sem_a",
        "cred_mat_sem_b",
        "cred_mat_anu",
        "cred_mat_total",
        "cred_sup_sem_a",
        "cred_sup_sem_b",
        "cred_sup_anu",
        "cred_sup_total",
        "cred_sup_1o",
        "cred_sup_2o",
        "cred_sup_3o",
        "cred_sup_4o",
        "cred_sup_5o",
        "cred_sup_6o",
        "cred_sup_tit",
        "cred_pend_sup_tit"
    ],

    "Enrollment / Administrative": [
        "matricula_activa",
        "baja_fecha",
        "impagado_curso_mat"
    ],

    "Student Activities": [
        "practicas",
        "actividades",
        "ajuste",
        "asig1",
        "pract1",
        "activ1",
        "total1",
        "ajuste1"
    ],

    "Target": [
        "abandono_hash"
    ]
}


# Temporal feature prefixes
TEMPORAL_FEATURE_PREFIXES = [
    "pft_events_",
    "pft_visits_",
    "pft_days_logged_",
    "pft_assignment_submissions_",
    "pft_test_submissions_",
    "pft_total_minutes_",
    "resource_events_",
    "n_resource_days_",
    "n_wifi_days_"
]


def get_feature_group(column):

    # Check explicitly defined columns first
    for group, columns in FEATURE_GROUP_RULES.items():
        if column in columns:
            return group

    # Check temporal/digital behaviour features
    for prefix in TEMPORAL_FEATURE_PREFIXES:
        if column.startswith(prefix):
            return "Temporal / Digital Behavior"

    # Dataset timestamp
    if column == "fecha_datos":
        return "Temporal Metadata"

    # Any column not covered above
    return "Other / Uncategorized"


def create_feature_summary(df, dataset_name):

    rows = []

    for column in df.columns:

        rows.append({
            "Dataset": dataset_name,
            "Column": column,
            "Data Type": str(df[column].dtype),
            "Feature Group": get_feature_group(column),
            "Missing Count": int(df[column].isna().sum()),
            "Missing %": round(df[column].isna().mean() * 100, 2),
            "Unique Values": int(df[column].nunique(dropna=True))
        })

    return pd.DataFrame(rows)


# Create column-level feature summaries
feature_summary_2018 = create_feature_summary(
    df_2018,
    "2018"
)

feature_summary_2021 = create_feature_summary(
    df_2021,
    "2021"
)

feature_summary_2022 = create_feature_summary(
    df_2022,
    "2022"
)


# Combine all datasets
feature_summary_all = pd.concat(
    [
        feature_summary_2018,
        feature_summary_2021,
        feature_summary_2022
    ],
    ignore_index=True
)


# Display column-level summary
print("=" * 70)
print("FEATURE GROUP SUMMARY")
print("=" * 70)

display(feature_summary_all)


# Group-level summary for each dataset
print("\n" + "=" * 70)
print("FEATURE GROUP COUNTS")
print("=" * 70)

group_summary = (
    feature_summary_all
    .groupby(
        ["Dataset", "Feature Group"]
    )
    .agg(
        Number_of_Features=("Column", "count"),
        Total_Missing=("Missing Count", "sum"),
        Average_Missing_Percent=("Missing %", "mean")
    )
    .reset_index()
)

display(group_summary)


# Show uncategorized columns
print("\n" + "=" * 70)
print("UNCATEGORIZED COLUMNS")
print("=" * 70)

uncategorized = (
    feature_summary_all[
        feature_summary_all["Feature Group"] == "Other / Uncategorized"
    ][
        ["Dataset", "Column", "Data Type"]
    ]
)

display(uncategorized)

======================================================================
FEATURE GROUP SUMMARY
======================================================================

,Dataset,Column,Data Type,Feature Group,Missing Count,Missing %,Unique Values
0,2018,dni_hash,object,Student Identity,0,0.00,20233
1,2018,tit_hash,object,Student Identity,0,0.00,124
2,2018,asi_hash,object,Student Identity,0,0.00,3747
3,2018,anyo_ingreso,float64,Admission Information,32699,21.45,10
4,2018,tipo_ingreso,object,Admission Information,32699,21.45,15
...,...,...,...,...,...,...,...
520,2022,pft_test_submissions_2023_7,float64,Temporal / Digital Behavior,159148,99.98,4
521,2022,pft_total_minutes_2023_7,float64,Temporal / Digital Behavior,150318,94.44,8631
522,2022,n_wifi_days_2023_7,float64,Temporal / Digital Behavior,119762,75.24,24
523,2022,resource_events_2023_7,float64,Temporal / Digital Behavior,152711,95.94,68
524,2022,n_resource_days_2023_7,float64,Temporal / Digital Behavior,152711,95.94,7

======================================================================
FEATURE GROUP COUNTS
======================================================================

   Dataset                Feature Group  Number_of_Features  Total_Missing  Average_Missing_Percent
0     2018          Academic Background                   6         300994                32.905000
1     2018         Academic Performance                  10         945972                62.053000
2     2018        Admission Information                   5         103183                13.538000
3     2018              Course Progress                   2              0                 0.000000
4     2018           Credit Information                  29              0                 0.000000
5     2018  Enrollment / Administrative                   3         288443                63.070000
6     2018        Other / Uncategorized                   2          30413                 9.975000
7     2018           Student Activities                   8         718846                58.942500
8     2018             Student Identity                   3              0                 0.000000
9     2018                       Target                   1              0                 0.000000
10    2018  Temporal / Digital Behavior                 108       14344197                87.123519
11    2018            Temporal Metadata                   1              0                 0.000000
12    2021          Academic Background                   6         305563                33.261667
13    2021         Academic Performance                  10         461156                30.118000
14    2021        Admission Information                   5         113140                14.778000
15    2021              Course Progress                   2              0                 0.000000
16    2021           Credit Information                  29              0                 0.000000
17    2021  Enrollment / Administrative                   3         286596                62.393333
18    2021        Other / Uncategorized                   2          30988                10.120000
19    2021           Student Activities                   8         718336                58.641250
20    2021             Student Identity                   3              0                 0.000000
21    2021                       Target                   1              0                 0.000000
22    2021  Temporal / Digital Behavior                 108       11858694                71.710278
23    2021            Temporal Metadata                   1              0                 0.000000
24    2022          Academic Background                   6         317382                33.233333
25    2022         Academic Performance                  10         494690                31.079000
26    2022        Admission Information                   5         115492                14.512000
27    2022              Course Progress                   2              0                 0.000000
28    2022           Credit Information                  29              0                 0.000000
29    2022  Enrollment / Administrative                   3         298488                62.506667
30    2022        Other / Uncategorized                   2          31756                 9.975000
31    2022           Student Activities                   8         745853                58.572500
32    2022             Student Identity                   3              0                 0.000000
33    2022                       Target                   1              0                 0.000000
34    2022  Temporal / Digital Behavior                  99       10828583                68.717576
35    2022            Temporal Metadata                   1              0                 0.000000

======================================================================
UNCATEGORIZED COLUMNS
======================================================================

    Dataset                       Column Data Type
15     2018                         caca     int64
16     2018  grupos_por_tipocredito_hash    object
193    2021                         caca     int64
194    2021  grupos_por_tipocredito_hash    object
371    2022                         caca     int64
372    2022  grupos_por_tipocredito_hash    object

# SECTION 11: Target & Temporal Relationship

In [ ]:
#Target values
for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:

    print(f"\n===== {year} =====")
    print(df["abandono_hash"].value_counts(dropna=False))
    print("\nPercentage:")
    print(
        df["abandono_hash"]
        .value_counts(normalize=True, dropna=False)
        .mul(100)
        .round(2)
    )

===== 2018 =====
abandono_hash
B    142567
A      9879
Name: count, dtype: int64

Percentage:
abandono_hash
B    93.52
A     6.48
Name: proportion, dtype: float64

===== 2021 =====
abandono_hash
B    144177
A      8943
Name: count, dtype: int64

Percentage:
abandono_hash
B    94.16
A     5.84
Name: proportion, dtype: float64

===== 2022 =====
abandono_hash
B    148384
A     10789
Name: count, dtype: int64

Percentage:
abandono_hash
B    93.22
A     6.78
Name: proportion, dtype: float64

In [ ]:
#Target vs withdrawal date
for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:

    print(f"\n===== {year} =====")

    print("baja_fecha dtype:", df["baja_fecha"].dtype)
    print("Non-null:", df["baja_fecha"].notna().sum())
    print("Null:", df["baja_fecha"].isna().sum())

    print("\nSample:")
    print(df["baja_fecha"].dropna().head())

===== 2018 =====
baja_fecha dtype: object
Non-null: 13191
Null: 139255

Sample:
16    2019-02-28
17    2019-03-04
18    2019-02-28
19    2019-03-04
52    2019-05-23
Name: baja_fecha, dtype: object

===== 2021 =====
baja_fecha dtype: object
Non-null: 15763
Null: 137357

Sample:
8     2022-07-28
11    2022-07-28
12    2022-06-28
13    2022-07-28
15    2022-07-28
Name: baja_fecha, dtype: object

===== 2022 =====
baja_fecha dtype: object
Non-null: 16220
Null: 142953

Sample:
18    2023-01-26
19    2023-01-26
51    2023-07-17
52    2023-07-17
53    2023-07-17
Name: baja_fecha, dtype: object

# SECTION 12: Check Target Consistency

In [ ]:
for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:

    print(f"\n===== {year} =====")

    print(
        pd.crosstab(
            df["abandono_hash"],
            df["baja_fecha"].notna(),
            margins=True
        )
    )

===== 2018 =====
baja_fecha      False   True     All
abandono_hash
A                9370    509    9879
B              129885  12682  142567
All            139255  13191  152446

===== 2021 =====
baja_fecha      False   True     All
abandono_hash
A                8374    569    8943
B              128983  15194  144177
All            137357  15763  153120

===== 2022 =====
baja_fecha      False   True     All
abandono_hash
A               10184    605   10789
B              132769  15615  148384
All            142953  16220  159173

# SECTION 13: Target and Withdrawal Date Audit

In [ ]:
for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:

    print(f"\n{'='*60}")
    print(f"DATASET: {year}")
    print(f"{'='*60}")

    # Target values
    print("\nTarget values:")
    print(df["abandono_hash"].value_counts(dropna=False))

    # Target vs baja_fecha availability
    print("\nTarget vs baja_fecha availability:")

    audit = pd.crosstab(
        df["abandono_hash"],
        df["baja_fecha"].notna(),
        margins=True
    )

    print(audit)

============================================================
DATASET: 2018
============================================================

Target values:
abandono_hash
B    142567
A      9879
Name: count, dtype: int64

Target vs baja_fecha availability:
baja_fecha      False   True     All
abandono_hash
A                9370    509    9879
B              129885  12682  142567
All            139255  13191  152446

============================================================
DATASET: 2021
============================================================

Target values:
abandono_hash
B    144177
A      8943
Name: count, dtype: int64

Target vs baja_fecha availability:
baja_fecha      False   True     All
abandono_hash
A                8374    569    8943
B              128983  15194  144177
All            137357  15763  153120

============================================================
DATASET: 2022
============================================================

Target values:
abandono_hash
B    148384
A     10789
Name: count, dtype: int64

Target vs baja_fecha availability:
baja_fecha      False   True     All
abandono_hash
A               10184    605   10789
B              132769  15615  148384
All            142953  16220  159173

In [ ]:
# Convert withdrawal date safely

for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:

    temp = pd.to_datetime(
        df["baja_fecha"],
        errors="coerce"
    )

    print(f"\n===== {year} =====")
    print("Earliest:", temp.min())
    print("Latest:", temp.max())

===== 2018 =====
Earliest: 2018-07-18 00:00:00
Latest: 2023-06-28 00:00:00

===== 2021 =====
Earliest: 2021-07-21 00:00:00
Latest: 2023-04-03 00:00:00

===== 2022 =====
Earliest: 2022-06-21 00:00:00
Latest: 2023-11-20 00:00:00

# SECTION 14: Student Record Distribution

In [ ]:
for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:

    records_per_student = df.groupby("dni_hash").size()

    print(f"\n===== {year} =====")
    print("Unique students:", records_per_student.shape[0])
    print("Mean records/student:", records_per_student.mean())
    print("Median:", records_per_student.median())
    print("Min:", records_per_student.min())
    print("Max:", records_per_student.max())

    print("\nDistribution:")
    print(records_per_student.value_counts().sort_index().head(20))

===== 2018 =====
Unique students: 20233
Mean records/student: 7.534522809271982
Median: 8.0
Min: 1
Max: 46

Distribution:
1     2630
2      833
3      661
4      588
5     1782
6      985
7     1792
8     1978
9     2338
10    2377
11    1558
12    1186
13     641
14     207
15     150
16      75
17      96
18     110
19      71
20      32
Name: count, dtype: int64

===== 2021 =====
Unique students: 20264
Mean records/student: 7.556257402289775
Median: 8.0
Min: 1
Max: 44

Distribution:
1     2539
2      645
3      577
4      619
5     1826
6     1126
7     1541
8     2303
9     2521
10    2548
11    1476
12    1110
13     616
14     217
15     124
16      63
17     116
18     105
19      65
20      32
Name: count, dtype: int64

===== 2022 =====
Unique students: 20427
Mean records/student: 7.79228472120233
Median: 8.0
Min: 1
Max: 47

Distribution:
1     2419
2      569
3      563
4      533
5     1673
6     1304
7     1668
8     2073
9     2499
10    2744
11    1468
12    1236
13     694
14     251
15     172
16     100
17      93
18      84
19      95
20      56
Name: count, dtype: int64

# SECTION 15: Target Consistency per Student

In [ ]:
for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:

    target_variation = (
        df.groupby("dni_hash")["abandono_hash"]
        .nunique()
    )

    inconsistent = (target_variation > 1).sum()

    print(f"\n===== {year} =====")
    print("Unique students:", len(target_variation))
    print("Students with multiple target values:", inconsistent)
    print(
        "Percentage:",
        round(inconsistent / len(target_variation) * 100, 4),
        "%"
    )

===== 2018 =====
Unique students: 20233
Students with multiple target values: 0
Percentage: 0.0 %

===== 2021 =====
Unique students: 20264
Students with multiple target values: 0
Percentage: 0.0 %

===== 2022 =====
Unique students: 20427
Students with multiple target values: 0
Percentage: 0.0 %

# SECTION 16: Withdrawal Date Consistency

In [ ]:
for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:

    date_variation = (
        df.groupby("dni_hash")["baja_fecha"]
        .nunique(dropna=True)
    )

    multiple_dates = (date_variation > 1).sum()

    print(f"\n===== {year} =====")
    print("Students with multiple withdrawal dates:", multiple_dates)

===== 2018 =====
Students with multiple withdrawal dates: 493

===== 2021 =====
Students with multiple withdrawal dates: 456

===== 2022 =====
Students with multiple withdrawal dates: 518

# SECTION 17: Temporal / Academic Structure Audit

In [ ]:
important_cols = [
    "dni_hash",
    "abandono_hash",
    "anyo_ingreso",
    "anyo_inicio_estudios",
    "fecha_datos",
    "curso_mas_bajo",
    "curso_mas_alto",
    "baja_fecha"
]

for year, df in [
    (2018, df_2018),
    (2021, df_2021),
    (2022, df_2022)
]:

    print(f"\n{'='*70}")
    print(f"DATASET {year}")
    print(f"{'='*70}")

    for col in important_cols:
        if col in df.columns:
            print(f"\n--- {col} ---")
            print("dtype:", df[col].dtype)
            print("unique:", df[col].nunique(dropna=True))
            print("missing:", df[col].isna().sum())

            if df[col].nunique(dropna=True) <= 20:
                print(df[col].value_counts(dropna=False).head(20))
            else:
                print(df[col].head(10).to_list())

======================================================================
DATASET 2018
======================================================================

--- dni_hash ---
dtype: object
unique: 20233
missing: 0
['922787046182', '922787046182', '922787046182', '922787046182', '922787046182', '922787046182', '922787046182', '922787046182', '922787046182', '922787046182']

--- abandono_hash ---
dtype: object
unique: 2
missing: 0
abandono_hash
B    142567
A      9879
Name: count, dtype: int64

--- anyo_ingreso ---
dtype: float64
unique: 10
missing: 32699
anyo_ingreso
NaN       32699
2018.0    29825
2016.0    26188
2015.0    25839
2017.0    23264
2014.0     9888
2013.0     2557
2012.0     1145
2011.0      586
2010.0      413
2009.0       42
Name: count, dtype: int64

--- anyo_inicio_estudios ---
dtype: int64
unique: 16
missing: 0
anyo_inicio_estudios
2018    52843
2017    30472
2016    27101
2015    26238
2014    10291
2013     2712
2012     1237
2011      675
2010      450
2019      240
2020       72
2009       55
2021       34
2022       24
2007        1
2008        1
Name: count, dtype: int64

--- fecha_datos ---
dtype: object
unique: 1
missing: 0
fecha_datos
2023-06-28 16:04:41    152446
Name: count, dtype: int64

--- curso_mas_bajo ---
dtype: int64
unique: 6
missing: 0
curso_mas_bajo
1    63047
2    40288
3    30225
4    17410
5     1346
6      130
Name: count, dtype: int64

--- curso_mas_alto ---
dtype: int64
unique: 6
missing: 0
curso_mas_alto
1    49513
4    37807
2    31107
3    29456
5     4184
6      379
Name: count, dtype: int64

--- baja_fecha ---
dtype: object
unique: 271
missing: 139255
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

======================================================================
DATASET 2021
======================================================================

--- dni_hash ---
dtype: object
unique: 20264
missing: 0
['319636fc9270', '319636fc9270', '319636fc9270', '319636fc9270', '319636fc9270', '319636fc9270', '319636fc9270', '319636fc9270', 'd6968ebe9360', 'd6968ebe9360']

--- abandono_hash ---
dtype: object
unique: 2
missing: 0
abandono_hash
B    144177
A      8943
Name: count, dtype: int64

--- anyo_ingreso ---
dtype: float64
unique: 13
missing: 37358
anyo_ingreso
NaN       37358
2018.0    27009
2021.0    26969
2019.0    26324
2020.0    22802
2017.0     7309
2016.0     2708
2015.0     1290
2014.0      753
2013.0      231
2012.0      156
2011.0      113
2010.0       77
2009.0       21
Name: count, dtype: int64

--- anyo_inicio_estudios ---
dtype: int64
unique: 17
missing: 0
anyo_inicio_estudios
2021    53603
2020    30799
2018    27416
2019    27382
2017     7663
2016     2932
2015     1440
2014      903
2013      271
2022      217
2012      198
2011      162
2010       94
2009       27
2023       10
2008        2
2006        1
Name: count, dtype: int64

--- fecha_datos ---
dtype: object
unique: 1
missing: 0
fecha_datos
2023-06-28 14:19:30    153120
Name: count, dtype: int64

--- curso_mas_bajo ---
dtype: int64
unique: 6
missing: 0
curso_mas_bajo
1    66853
2    34836
3    32508
4    17849
5     1015
6       59
Name: count, dtype: int64

--- curso_mas_alto ---
dtype: int64
unique: 6
missing: 0
curso_mas_alto
1    53457
4    38224
2    30821
3    27118
5     3438
6       62
Name: count, dtype: int64

--- baja_fecha ---
dtype: object
unique: 281
missing: 137357
[nan, nan, nan, nan, nan, nan, nan, nan, '2022-07-28', nan]

======================================================================
DATASET 2022
======================================================================

--- dni_hash ---
dtype: object
unique: 20427
missing: 0
['319636fc9270', '319636fc9270', '319636fc9270', '319636fc9270', '319636fc9270', '319636fc9270', '319636fc9270', '319636fc9270', '319636fc9270', '319636fc9270']

--- abandono_hash ---
dtype: object
unique: 2
missing: 0
abandono_hash
B    148384
A     10789
Name: count, dtype: int64

--- anyo_ingreso ---
dtype: float64
unique: 16
missing: 37821
anyo_ingreso
NaN       37821
2022.0    30995
2020.0    26029
2019.0    25995
2021.0    25820
2018.0     7530
2017.0     2588
2016.0     1056
2015.0      541
2014.0      419
2013.0      137
2012.0       85
2010.0       74
2011.0       50
2009.0       21
2023.0       11
2007.0        1
Name: count, dtype: int64

--- anyo_inicio_estudios ---
dtype: int64
unique: 16
missing: 0
anyo_inicio_estudios
2022    58277
2021    33529
2020    27190
2019    26457
2018     7841
2017     2795
2016     1242
2015      704
2014      536
2023      180
2013      154
2012       96
2010       83
2011       63
2009       25
2007        1
Name: count, dtype: int64

--- fecha_datos ---
dtype: object
unique: 1
missing: 0
fecha_datos
2023-11-20 12:04:51    159173
Name: count, dtype: int64

--- curso_mas_bajo ---
dtype: int64
unique: 5
missing: 0
curso_mas_bajo
1    72502
2    39711
3    28486
4    17241
5     1233
Name: count, dtype: int64

--- curso_mas_alto ---
dtype: int64
unique: 5
missing: 0
curso_mas_alto
1    55580
2    35835
4    35436
3    28280
5     4042
Name: count, dtype: int64

--- baja_fecha ---
dtype: object
unique: 251
missing: 142953
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

# SECTION 18: Sample Longitudinal Records

In [ ]:
student_sample = df_2018["dni_hash"].value_counts()

sample_student = student_sample.index[0]

print("Selected student:", sample_student)

student_records = (
    df_2018[df_2018["dni_hash"] == sample_student]
    .sort_values("fecha_datos")
)

display(
    student_records[
        [
            "dni_hash",
            "abandono_hash",
            "anyo_ingreso",
            "anyo_inicio_estudios",
            "fecha_datos",
            "curso_mas_bajo",
            "curso_mas_alto",
            "baja_fecha"
        ]
    ]
)

Selected student: 481818ccb4bd

,dni_hash,abandono_hash,anyo_ingreso,anyo_inicio_estudios,fecha_datos,curso_mas_bajo,curso_mas_alto,baja_fecha
98642,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98667,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98668,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98669,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98670,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98671,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,2018-09-20
98672,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,2019-01-14
98673,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,2019-01-14
98674,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,2018-09-20
98675,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,2018-09-20
98676,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98677,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98678,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98679,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98680,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98681,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98682,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98683,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98684,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98685,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,2019-01-14
98666,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98665,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98664,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98663,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98643,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98644,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98645,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98646,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98647,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98648,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98649,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98650,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98651,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98686,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,2019-01-14
98652,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98654,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98655,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98656,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98657,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98658,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98659,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98660,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98661,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98662,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98653,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN
98687,481818ccb4bd,B,2018.0,2018,2023-06-28 16:04:41,4,6,NaN

#  SECTION 19: FINAL DATA QUALITY / AUDIT SUMMARY

In [ ]:
print("=" * 70)
print("FINAL DATA QUALITY / AUDIT SUMMARY")
print("=" * 70)

for year, df in datasets.items():

    print("\n" + "=" * 70)
    print(f"DATASET: {year}")
    print("=" * 70)

    # --------------------------------------------------------------
    # Basic structure
    # --------------------------------------------------------------
    print("\n[1] Dataset Structure")
    print(f"Rows: {len(df):,}")
    print(f"Columns: {len(df.columns):,}")

    # --------------------------------------------------------------
    # Student identifier
    # --------------------------------------------------------------
    if "dni_hash" in df.columns:
        print("\n[2] Student Identity")
        print(f"Unique students: {df['dni_hash'].nunique():,}")
        print(f"Missing student IDs: {df['dni_hash'].isna().sum():,}")

    # --------------------------------------------------------------
    # Target
    # --------------------------------------------------------------
    if "abandono_hash" in df.columns:
        print("\n[3] Target Variable")

        target_counts = df["abandono_hash"].value_counts(dropna=False)

        print("Target distribution:")
        print(target_counts)

        target_pct = (
            df["abandono_hash"]
            .value_counts(normalize=True, dropna=False)
            .mul(100)
            .round(2)
        )

        print("Target percentage:")
        print(target_pct)

    # --------------------------------------------------------------
    # Missing values
    # --------------------------------------------------------------
    print("\n[4] Missing Data")

    total_missing = int(df.isna().sum().sum())
    total_cells = df.shape[0] * df.shape[1]
    missing_pct = (total_missing / total_cells * 100) if total_cells else 0

    print(f"Total missing cells: {total_missing:,}")
    print(f"Overall missing percentage: {missing_pct:.2f}%")

    # --------------------------------------------------------------
    # Withdrawal date
    # --------------------------------------------------------------
    if "baja_fecha" in df.columns:
        print("\n[5] Withdrawal Date")

        available = df["baja_fecha"].notna().sum()
        missing = df["baja_fecha"].isna().sum()

        print(f"Available: {available:,} ({available / len(df) * 100:.2f}%)")
        print(f"Missing:   {missing:,} ({missing / len(df) * 100:.2f}%)")

    # --------------------------------------------------------------
    # Duplicate rows
    # --------------------------------------------------------------
    print("\n[6] Duplicate Rows")
    duplicates = df.duplicated().sum()
    print(f"Duplicate rows: {duplicates:,}")

    # --------------------------------------------------------------
    # Unique students with multiple target values
    # --------------------------------------------------------------
    if "dni_hash" in df.columns and "abandono_hash" in df.columns:

        target_per_student = df.groupby("dni_hash")["abandono_hash"].nunique()

        multiple_targets = (target_per_student > 1).sum()

        print("\n[7] Target Consistency per Student")
        print(f"Students with multiple target values: {multiple_targets:,}")

    # --------------------------------------------------------------
    # Multiple withdrawal dates
    # --------------------------------------------------------------
    if "dni_hash" in df.columns and "baja_fecha" in df.columns:

        withdrawal_per_student = (
            df.dropna(subset=["baja_fecha"])
              .groupby("dni_hash")["baja_fecha"]
              .nunique()
        )

        multiple_withdrawals = (withdrawal_per_student > 1).sum()

        print("\n[8] Withdrawal Date Consistency")
        print(f"Students with multiple withdrawal dates: {multiple_withdrawals:,}")

print("\n" + "=" * 70)
print("AUDIT SUMMARY COMPLETED")
print("=" * 70)

======================================================================
FINAL DATA QUALITY / AUDIT SUMMARY
======================================================================

======================================================================
DATASET: 2018
======================================================================

[1] Dataset Structure
Rows: 152,446
Columns: 178

[2] Student Identity
Unique students: 20,233
Missing student IDs: 0

[3] Target Variable
Target distribution:
abandono_hash
B    142567
A      9879
Name: count, dtype: int64
Target percentage:
abandono_hash
B    93.52
A     6.48
Name: proportion, dtype: float64

[4] Missing Data
Total missing cells: 16,732,048
Overall missing percentage: 61.66%

[5] Withdrawal Date
Available: 13,191 (8.65%)
Missing:   139,255 (91.35%)

[6] Duplicate Rows
Duplicate rows: 0

[7] Target Consistency per Student
Students with multiple target values: 0

[8] Withdrawal Date Consistency
Students with multiple withdrawal dates: 493

======================================================================
DATASET: 2021
======================================================================

[1] Dataset Structure
Rows: 153,120
Columns: 178

[2] Student Identity
Unique students: 20,264
Missing student IDs: 0

[3] Target Variable
Target distribution:
abandono_hash
B    144177
A      8943
Name: count, dtype: int64
Target percentage:
abandono_hash
B    94.16
A     5.84
Name: proportion, dtype: float64

[4] Missing Data
Total missing cells: 13,774,473
Overall missing percentage: 50.54%

[5] Withdrawal Date
Available: 15,763 (10.29%)
Missing:   137,357 (89.71%)

[6] Duplicate Rows
Duplicate rows: 0

[7] Target Consistency per Student
Students with multiple target values: 0

[8] Withdrawal Date Consistency
Students with multiple withdrawal dates: 456

======================================================================
DATASET: 2022
======================================================================

[1] Dataset Structure
Rows: 159,173
Columns: 169

[2] Student Identity
Unique students: 20,427
Missing student IDs: 0

[3] Target Variable
Target distribution:
abandono_hash
B    148384
A     10789
Name: count, dtype: int64
Target percentage:
abandono_hash
B    93.22
A     6.78
Name: proportion, dtype: float64

[4] Missing Data
Total missing cells: 12,832,244
Overall missing percentage: 47.70%

[5] Withdrawal Date
Available: 16,220 (10.19%)
Missing:   142,953 (89.81%)

[6] Duplicate Rows
Duplicate rows: 0

[7] Target Consistency per Student
Students with multiple target values: 0

[8] Withdrawal Date Consistency
Students with multiple withdrawal dates: 518

======================================================================
AUDIT SUMMARY COMPLETED
======================================================================

# SECTION 20: Data Dictionary + Feature Meaning

In [ ]:
import re
import pandas as pd

print("=" * 70)
print("DATA DICTIONARY + FEATURE MEANING")
print("=" * 70)


# ----------------------------------------------------------------------
# Feature group rules
# ----------------------------------------------------------------------

FEATURE_GROUP_RULES = {

    "Student Identity": [
        "dni_hash",
        "tit_hash",
        "asi_hash"
    ],

    "Target": [
        "abandono_hash"
    ],

    "Admission Information": [
        "anyo_ingreso",
        "tipo_ingreso"
    ],

    "Temporal Metadata": [
        "fecha_datos"
    ],

    "Course Progress": [
        "curso_mas_bajo",
        "curso_mas_alto"
    ],

    "Withdrawal Information": [
        "baja_fecha"
    ]
}


# ----------------------------------------------------------------------
# Determine feature group
# ----------------------------------------------------------------------

def get_feature_group(column):

    # Exact match
    for group, columns in FEATURE_GROUP_RULES.items():
        if column in columns:
            return group

    # Temporal / digital behaviour
    temporal_prefixes = (
        "pft_",
        "n_resource_",
        "n_wifi_",
        "resource_events_"
    )

    if column.startswith(temporal_prefixes):
        return "Temporal / Digital Behavior"

    # Academic / credit related naming patterns
    academic_keywords = [
        "nota",
        "calificacion",
        "grade",
        "exam",
        "evaluacion",
        "rendimiento"
    ]

    if any(keyword in column.lower() for keyword in academic_keywords):
        return "Academic Performance"

    credit_keywords = [
        "credito",
        "credit"
    ]

    if any(keyword in column.lower() for keyword in credit_keywords):
        return "Credit Information"

    # Enrollment / administrative
    enrollment_keywords = [
        "matricula",
        "enrollment",
        "inscripcion",
        "administr"
    ]

    if any(keyword in column.lower() for keyword in enrollment_keywords):
        return "Enrollment / Administrative"

    # Activity related
    activity_keywords = [
        "actividad",
        "activity",
        "participacion",
        "participation"
    ]

    if any(keyword in column.lower() for keyword in activity_keywords):
        return "Student Activities"

    return "Other / Uncategorized"


# ----------------------------------------------------------------------
# Identify temporal feature
# ----------------------------------------------------------------------

def is_temporal_feature(column):

    temporal_prefixes = (
        "pft_",
        "n_resource_",
        "n_wifi_",
        "resource_events_"
    )

    return column.startswith(temporal_prefixes)


# ----------------------------------------------------------------------
# Generate feature meaning
# ----------------------------------------------------------------------

def get_feature_meaning(column):

    # Known fields
    known_meanings = {

        "dni_hash":
            "Anonymized student identifier.",

        "tit_hash":
            "Anonymized identifier associated with the academic entity.",

        "asi_hash":
            "Anonymized identifier associated with the academic record.",

        "abandono_hash":
            "Binary dropout/withdrawal target variable.",

        "anyo_ingreso":
            "Year of admission.",

        "tipo_ingreso":
            "Type or category of admission.",

        "anyo_inicio_estudios":
            "Year in which the student's studies began.",

        "fecha_datos":
            "Timestamp representing the dataset observation/data extraction date.",

        "curso_mas_bajo":
            "Lowest course level recorded for the student.",

        "curso_mas_alto":
            "Highest course level recorded for the student.",

        "baja_fecha":
            "Date associated with student withdrawal/dropout."
    }

    if column in known_meanings:
        return known_meanings[column]

    # Temporal features
    temporal_match = re.search(
        r"(.+)_(\d{4})_(\d{1,2})$",
        column
    )

    if temporal_match:

        base_name = temporal_match.group(1)
        year = temporal_match.group(2)
        month = temporal_match.group(3).zfill(2)

        meaning_map = {

            "pft_events":
                "Number of platform events",

            "pft_visits":
                "Number of platform visits",

            "pft_days_logged":
                "Number of days with platform activity",

            "pft_assignment_submissions":
                "Number of assignment submissions",

            "pft_test_submissions":
                "Number of test submissions",

            "pft_total_minutes":
                "Total platform usage time in minutes",

            "n_wifi_days":
                "Number of days with Wi-Fi activity",

            "resource_events":
                "Number of resource-related events",

            "n_resource_days":
                "Number of days with resource activity"
        }

        base_meaning = meaning_map.get(
            base_name,
            "Temporal/digital behaviour measure"
        )

        return f"{base_meaning} during {year}-{month}."

    # Fallback
    return "Meaning requires verification from the original UPV documentation/codebook."


# ----------------------------------------------------------------------
# Build data dictionary
# ----------------------------------------------------------------------

data_dictionary = []

for year, df in datasets.items():

    for column in df.columns:

        missing_count = int(df[column].isna().sum())
        missing_pct = (
            missing_count / len(df) * 100
            if len(df) > 0 else 0
        )

        data_dictionary.append({

            "Dataset": year,
            "Column": column,
            "Data Type": str(df[column].dtype),
            "Feature Group": get_feature_group(column),
            "Meaning": get_feature_meaning(column),
            "Missing Count": missing_count,
            "Missing %": round(missing_pct, 2),
            "Unique Values": int(df[column].nunique(dropna=True)),
            "Temporal Feature": is_temporal_feature(column)

        })


data_dictionary_df = pd.DataFrame(data_dictionary)


# ----------------------------------------------------------------------
# Display
# ----------------------------------------------------------------------

print("\nTotal dictionary entries:",
      len(data_dictionary_df))

display(data_dictionary_df.head(20))


print("\n" + "=" * 70)
print("FEATURE GROUP DISTRIBUTION")
print("=" * 70)

display(
    data_dictionary_df
    .groupby(["Dataset", "Feature Group"])
    .size()
    .reset_index(name="Number of Features")
)


print("\n" + "=" * 70)
print("UNCATEGORIZED FEATURES")
print("=" * 70)

uncategorized = data_dictionary_df[
    data_dictionary_df["Feature Group"] == "Other / Uncategorized"
]

display(uncategorized)

======================================================================
DATA DICTIONARY + FEATURE MEANING
======================================================================

Total dictionary entries: 525

,Dataset,Column,Data Type,Feature Group,Meaning,Missing Count,Missing %,Unique Values,Temporal Feature
0,2018,dni_hash,object,Student Identity,Anonymized student identifier.,0,0.00,20233,False
1,2018,tit_hash,object,Student Identity,Anonymized identifier associated with the acad...,0,0.00,124,False
2,2018,asi_hash,object,Student Identity,Anonymized identifier associated with the acad...,0,0.00,3747,False
3,2018,anyo_ingreso,float64,Admission Information,Year of admission.,32699,21.45,10,False
4,2018,tipo_ingreso,object,Admission Information,Type or category of admission.,32699,21.45,15,False
5,2018,nota10_hash,float64,Academic Performance,Meaning requires verification from the origina...,37559,24.64,3590,False
6,2018,nota14_hash,float64,Academic Performance,Meaning requires verification from the origina...,38296,25.12,5583,False
7,2018,campus_hash,object,Other / Uncategorized,Meaning requires verification from the origina...,0,0.00,40,False
8,2018,estudios_p_hash,object,Other / Uncategorized,Meaning requires verification from the origina...,906,0.59,6,False
9,2018,estudios_m_hash,object,Other / Uncategorized,Meaning requires verification from the origina...,906,0.59,6,False
10,2018,dedicacion,object,Other / Uncategorized,Meaning requires verification from the origina...,0,0.00,2,False
11,2018,desplazado_hash,object,Other / Uncategorized,Meaning requires verification from the origina...,0,0.00,2,False
12,2018,abandono_hash,object,Target,Binary dropout/withdrawal target variable.,0,0.00,2,False
13,2018,preferencia_seleccion,float64,Other / Uncategorized,Meaning requires verification from the origina...,37785,24.79,18,False
14,2018,baja_fecha,object,Withdrawal Information,Date associated with student withdrawal/dropout.,139255,91.35,271,False
15,2018,caca,int64,Other / Uncategorized,Meaning requires verification from the origina...,0,0.00,1,False
16,2018,grupos_por_tipocredito_hash,object,Credit Information,Meaning requires verification from the origina...,30413,19.95,7013,False
17,2018,matricula_activa,float64,Enrollment / Administrative,Meaning requires verification from the origina...,0,0.00,2,False
18,2018,nota_asig_hash,float64,Academic Performance,Meaning requires verification from the origina...,12649,8.30,98,False
19,2018,fecha_datos,object,Temporal Metadata,Timestamp representing the dataset observation...,0,0.00,1,False

======================================================================
FEATURE GROUP DISTRIBUTION
======================================================================

   Dataset                Feature Group  Number of Features
0     2018         Academic Performance                   6
1     2018        Admission Information                   2
2     2018              Course Progress                   2
3     2018           Credit Information                   1
4     2018  Enrollment / Administrative                   1
5     2018        Other / Uncategorized                  51
6     2018           Student Activities                   1
7     2018             Student Identity                   3
8     2018                       Target                   1
9     2018  Temporal / Digital Behavior                 108
10    2018            Temporal Metadata                   1
11    2018       Withdrawal Information                   1
12    2021         Academic Performance                   6
13    2021        Admission Information                   2
14    2021              Course Progress                   2
15    2021           Credit Information                   1
16    2021  Enrollment / Administrative                   1
17    2021        Other / Uncategorized                  51
18    2021           Student Activities                   1
19    2021             Student Identity                   3
20    2021                       Target                   1
21    2021  Temporal / Digital Behavior                 108
22    2021            Temporal Metadata                   1
23    2021       Withdrawal Information                   1
24    2022         Academic Performance                   6
25    2022        Admission Information                   2
26    2022              Course Progress                   2
27    2022           Credit Information                   1
28    2022  Enrollment / Administrative                   1
29    2022        Other / Uncategorized                  51
30    2022           Student Activities                   1
31    2022             Student Identity                   3
32    2022                       Target                   1
33    2022  Temporal / Digital Behavior                  99
34    2022            Temporal Metadata                   1
35    2022       Withdrawal Information                   1

======================================================================
UNCATEGORIZED FEATURES
======================================================================

,Dataset,Column,Data Type,Feature Group,Meaning,Missing Count,Missing %,Unique Values,Temporal Feature
7,2018,campus_hash,object,Other / Uncategorized,Meaning requires verification from the origina...,0,0.00,40,False
8,2018,estudios_p_hash,object,Other / Uncategorized,Meaning requires verification from the origina...,906,0.59,6,False
9,2018,estudios_m_hash,object,Other / Uncategorized,Meaning requires verification from the origina...,906,0.59,6,False
10,2018,dedicacion,object,Other / Uncategorized,Meaning requires verification from the origina...,0,0.00,2,False
11,2018,desplazado_hash,object,Other / Uncategorized,Meaning requires verification from the origina...,0,0.00,2,False
...,...,...,...,...,...,...,...,...,...
421,2022,total1,float64,Other / Uncategorized,Meaning requires verification from the origina...,157656,99.05,144,False
422,2022,ajuste1,int64,Other / Uncategorized,Meaning requires verification from the origina...,0,0.00,1,False
423,2022,rend_total_ultimo,float64,Other / Uncategorized,Meaning requires verification from the origina...,58457,36.73,727,False
424,2022,rend_total_penultimo,float64,Other / Uncategorized,Meaning requires verification from the origina...,91986,57.79,575,False
425,2022,rend_total_antepenultimo,float64,Other / Uncategorized,Meaning requires verification from the origina...,119176,74.87,443,False

# SECTION 21: RESEARCH-READY DATASET SUMMARY

In [ ]:
print("=" * 70)
print("RESEARCH-READY DATASET SUMMARY")
print("=" * 70)


# ----------------------------------------------------------------------
# 1. Dataset-level summary
# ----------------------------------------------------------------------

summary_rows = []

for year, df in datasets.items():

    unique_students = (
        df["dni_hash"].nunique()
        if "dni_hash" in df.columns
        else None
    )

    target_column = "abandono_hash"

    target_available = (
        target_column in df.columns
    )

    temporal_features = sum(
        is_temporal_feature(col)
        for col in df.columns
    )

    summary_rows.append({

        "Dataset": year,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Unique Students": unique_students,
        "Temporal Features": temporal_features,
        "Target Available": target_available

    })


research_summary_df = pd.DataFrame(summary_rows)


print("\nDATASET SUMMARY")
display(research_summary_df)


# ----------------------------------------------------------------------
# 2. Common columns across all datasets
# ----------------------------------------------------------------------

dataset_column_sets = {
    year: set(df.columns)
    for year, df in datasets.items()
}

common_columns = set.intersection(
    *dataset_column_sets.values()
)

print("\n" + "=" * 70)
print("COMMON COLUMNS ACROSS ALL DATASETS")
print("=" * 70)

print(f"Number of common columns: {len(common_columns)}")

print("\nCommon columns:")
for column in sorted(common_columns):
    print(column)


# ----------------------------------------------------------------------
# 3. Dataset-specific columns
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("DATASET-SPECIFIC COLUMNS")
print("=" * 70)

for year in datasets:

    other_years = [
        y for y in datasets
        if y != year
    ]

    other_columns = set.union(
        *(dataset_column_sets[y] for y in other_years)
    )

    unique_columns = (
        dataset_column_sets[year] - other_columns
    )

    print(
        f"\n{year}: "
        f"{len(unique_columns)} dataset-specific columns"
    )


# ----------------------------------------------------------------------
# 4. Target readiness
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("TARGET READINESS")
print("=" * 70)

for year, df in datasets.items():

    if "abandono_hash" not in df.columns:
        print(f"{year}: Target column NOT FOUND")
        continue

    target_counts = df["abandono_hash"].value_counts()

    print(f"\nDataset {year}")
    print("Target values:")
    print(target_counts.to_dict())

    print(
        "Target missing:",
        int(df["abandono_hash"].isna().sum())
    )


# ----------------------------------------------------------------------
# 5. Identifier handling recommendation
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("MODELING PREPARATION NOTES")
print("=" * 70)

print("""
1. dni_hash is an anonymized student identifier and should not be
   directly used as a predictive feature.

2. Target variable:
   abandono_hash

3. baja_fecha should be treated carefully because it is directly
   associated with withdrawal/dropout information and may introduce
   target leakage depending on the prediction time.

4. fecha_datos is dataset-level temporal metadata and should not
   automatically be treated as a student behavioural feature.

5. Temporal/digital behaviour variables require temporal alignment
   before combining datasets from different academic periods.

6. Features with extremely high missingness should be evaluated
   before model training.

7. Dataset-specific columns should not automatically be discarded;
   their research relevance and temporal comparability should first
   be evaluated.

8. The final modeling dataset should be created only after feature
   selection, leakage analysis, missing-value treatment, encoding,
   and temporal alignment.
""")


# ----------------------------------------------------------------------
# 6. Final audit status
# ----------------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL STATUS")
print("=" * 70)

print("""
The UPV datasets are structurally suitable for further research
after appropriate preprocessing.

The audit confirms:

- Multiple longitudinal records per student
- Consistent binary target within each student
- Temporal/digital behavioural features
- Different temporal observation windows across datasets
- Dataset-specific temporal columns
- Missing values that require treatment
- Potential leakage-sensitive variables such as withdrawal date

Therefore, the next stage is feature engineering and preprocessing,
not direct model training.
""")

======================================================================
RESEARCH-READY DATASET SUMMARY
======================================================================

DATASET SUMMARY

  Dataset    Rows  Columns  Unique Students  Temporal Features  Target Available
0    2018  152446      178            20233                108              True
1    2021  153120      178            20264                108              True
2    2022  159173      169            20427                 99              True

======================================================================
COMMON COLUMNS ACROSS ALL DATASETS
======================================================================
Number of common columns: 70

Common columns:
abandono_hash
activ1
actividades
ajuste
ajuste1
anyo_ingreso
anyo_inicio_estudios
asi_hash
asig1
baja_fecha
caca
campus_hash
cred_mat1
cred_mat2
cred_mat3
cred_mat4
cred_mat5
cred_mat6
cred_mat_anu
cred_mat_movilidad
cred_mat_normal
cred_mat_practicas
cred_mat_sem_a
cred_mat_sem_b
cred_mat_total
cred_pend_sup_tit
cred_ptes_acta
cred_sup
cred_sup_1o
cred_sup_2o
cred_sup_3o
cred_sup_4o
cred_sup_5o
cred_sup_6o
cred_sup_anu
cred_sup_espec
cred_sup_normal
cred_sup_sem_a
cred_sup_sem_b
cred_sup_tit
cred_sup_total
curso_mas_alto
curso_mas_bajo
dedicacion
desplazado_hash
dni_hash
es_adaptado
es_retitulado
estudios_m_hash
estudios_p_hash
exento_npp
fecha_datos
grupos_por_tipocredito_hash
impagado_curso_mat
matricula_activa
nota10_hash
nota14_hash
nota_asig_hash
pract1
practicas
preferencia_seleccion
rend_total_antepenultimo
rend_total_penultimo
rend_total_ultimo
rendimiento_cuat_a
rendimiento_cuat_b
rendimiento_total
tipo_ingreso
tit_hash
total1

======================================================================
DATASET-SPECIFIC COLUMNS
======================================================================

2018: 108 dataset-specific columns

2021: 108 dataset-specific columns

2022: 99 dataset-specific columns

======================================================================
TARGET READINESS
======================================================================

Dataset 2018
Target values:
{'B': 142567, 'A': 9879}
Target missing: 0

Dataset 2021
Target values:
{'B': 144177, 'A': 8943}
Target missing: 0

Dataset 2022
Target values:
{'B': 148384, 'A': 10789}
Target missing: 0

======================================================================
MODELING PREPARATION NOTES
======================================================================

1. dni_hash is an anonymized student identifier and should not be
   directly used as a predictive feature.

2. Target variable:
   abandono_hash

3. baja_fecha should be treated carefully because it is directly
   associated with withdrawal/dropout information and may introduce
   target leakage depending on the prediction time.

4. fecha_datos is dataset-level temporal metadata and should not
   automatically be treated as a student behavioural feature.

5. Temporal/digital behaviour variables require temporal alignment
   before combining datasets from different academic periods.

6. Features with extremely high missingness should be evaluated
   before model training.

7. Dataset-specific columns should not automatically be discarded;
   their research relevance and temporal comparability should first
   be evaluated.

8. The final modeling dataset should be created only after feature
   selection, leakage analysis, missing-value treatment, encoding,
   and temporal alignment.


======================================================================
FINAL STATUS
======================================================================

The UPV datasets are structurally suitable for further research
after appropriate preprocessing.

The audit confirms:

- Multiple longitudinal records per student
- Consistent binary target within each student
- Temporal/digital behavioural features
- Different temporal observation windows across datasets
- Dataset-specific temporal columns
- Missing values that require treatment
- Potential leakage-sensitive variables such as withdrawal date

Therefore, the next stage is feature engineering and preprocessing,
not direct model training.

In [ ]:
# ================================================================
# SECTION 22: SAVE AUDIT RESULTS
# ================================================================
#
# Purpose:
# Save the important outputs of the UPV data audit so that the
# preprocessing notebook can use the audit findings without
# repeating the complete audit process.
#
# Output directory:
# Results/Audit/
# ================================================================

# Create Audit results directory
AUDIT_RESULT_DIR = RESULT_DIR / "Audit"
AUDIT_RESULT_DIR.mkdir(parents=True, exist_ok=True)

print("=" * 70)
print("SAVING AUDIT RESULTS")
print("=" * 70)


# ----------------------------------------------------------------
# 1. Feature-level summary
# ----------------------------------------------------------------
# Contains:
# Dataset, Column, Data Type, Feature Group,
# Missing Count, Missing %, Unique Values

feature_summary_all.to_csv(
    AUDIT_RESULT_DIR / "feature_summary_all.csv",
    index=False
)

print("Saved: feature_summary_all.csv")


# ----------------------------------------------------------------
# 2. Feature-group summary
# ----------------------------------------------------------------
# Contains feature counts and missing-value statistics
# for each feature group in each dataset.

group_summary.to_csv(
    AUDIT_RESULT_DIR / "feature_group_summary.csv",
    index=False
)

print("Saved: feature_group_summary.csv")


# ----------------------------------------------------------------
# 3. Common columns across datasets
# ----------------------------------------------------------------
# Convert the common column list into a DataFrame
# so it can be reused later during preprocessing.

common_columns_df = pd.DataFrame({
    "Column": sorted(common_columns)
})

common_columns_df.to_csv(
    AUDIT_RESULT_DIR / "common_columns.csv",
    index=False
)

print("Saved: common_columns.csv")


# ----------------------------------------------------------------
# 4. Dataset-specific columns
# ----------------------------------------------------------------
# Store columns that are not common across all three datasets.

dataset_specific_rows = []

all_dataset_columns = {
    "2018": set(df_2018.columns),
    "2021": set(df_2021.columns),
    "2022": set(df_2022.columns)
}

for dataset_name, columns in all_dataset_columns.items():

    specific_columns = sorted(
        columns - set(common_columns)
    )

    for column in specific_columns:
        dataset_specific_rows.append({
            "Dataset": dataset_name,
            "Column": column
        })


dataset_specific_columns_df = pd.DataFrame(
    dataset_specific_rows
)

dataset_specific_columns_df.to_csv(
    AUDIT_RESULT_DIR / "dataset_specific_columns.csv",
    index=False
)

print("Saved: dataset_specific_columns.csv")


# ----------------------------------------------------------------
# 5. Target summary
# ----------------------------------------------------------------
# Summarize target distribution and missing target values
# for every dataset.

target_rows = []

for dataset_name, df in {
    "2018": df_2018,
    "2021": df_2021,
    "2022": df_2022
}.items():

    target_counts = df["abandono_hash"].value_counts()

    target_rows.append({
        "Dataset": dataset_name,
        "Total Records": len(df),
        "Target Missing": int(
            df["abandono_hash"].isna().sum()
        ),
        "Class_A_Count": int(
            target_counts.get("A", 0)
        ),
        "Class_B_Count": int(
            target_counts.get("B", 0)
        ),
        "Class_A_Percent": round(
            (target_counts.get("A", 0) / len(df)) * 100,
            2
        ),
        "Class_B_Percent": round(
            (target_counts.get("B", 0) / len(df)) * 100,
            2
        )
    })


target_summary_df = pd.DataFrame(target_rows)

target_summary_df.to_csv(
    AUDIT_RESULT_DIR / "target_summary.csv",
    index=False
)

print("Saved: target_summary.csv")


# ----------------------------------------------------------------
# 6. Audit decisions
# ----------------------------------------------------------------
# These are research/modeling decisions identified during the audit.
#
# They are saved separately so that the preprocessing stage has
# a documented basis for feature treatment.

audit_decisions = pd.DataFrame([
    {
        "Decision_ID": 1,
        "Feature_or_Area": "dni_hash",
        "Decision": "Exclude from predictive features",
        "Reason": "Anonymized student identifier; not a meaningful predictive variable."
    },
    {
        "Decision_ID": 2,
        "Feature_or_Area": "abandono_hash",
        "Decision": "Use as target variable",
        "Reason": "Binary dropout/withdrawal target."
    },
    {
        "Decision_ID": 3,
        "Feature_or_Area": "baja_fecha",
        "Decision": "Exclude initially; investigate leakage",
        "Reason": "Withdrawal date may directly reveal the dropout outcome."
    },
    {
        "Decision_ID": 4,
        "Feature_or_Area": "fecha_datos",
        "Decision": "Do not use as a direct behavioural feature",
        "Reason": "Dataset-level timestamp rather than student-level behaviour."
    },
    {
        "Decision_ID": 5,
        "Feature_or_Area": "Temporal / Digital Behavior",
        "Decision": "Require temporal alignment",
        "Reason": "Observation windows differ between datasets."
    },
    {
        "Decision_ID": 6,
        "Feature_or_Area": "High-missingness features",
        "Decision": "Evaluate before modeling",
        "Reason": "Very high missingness may reduce feature reliability."
    },
    {
        "Decision_ID": 7,
        "Feature_or_Area": "Dataset-specific columns",
        "Decision": "Evaluate before removal",
        "Reason": "Dataset-specific does not automatically mean irrelevant."
    },
    {
        "Decision_ID": 8,
        "Feature_or_Area": "Repeated student records",
        "Decision": "Preserve longitudinal structure during preprocessing",
        "Reason": "UPV data contains multiple records per student."
    }
])

audit_decisions.to_csv(
    AUDIT_RESULT_DIR / "audit_decisions.csv",
    index=False
)

print("Saved: audit_decisions.csv")


print("\n" + "=" * 70)
print("ALL AUDIT RESULTS SAVED")
print("=" * 70)

print(f"\nOutput directory:")
print(AUDIT_RESULT_DIR)

print("\nFiles:")
for file in sorted(AUDIT_RESULT_DIR.glob("*.csv")):
    print(f"- {file.name}")

======================================================================
SAVING AUDIT RESULTS
======================================================================
Saved: feature_summary_all.csv
Saved: feature_group_summary.csv
Saved: common_columns.csv
Saved: dataset_specific_columns.csv
Saved: target_summary.csv
Saved: audit_decisions.csv

======================================================================
ALL AUDIT RESULTS SAVED
======================================================================

Output directory:
/content/drive/MyDrive/Thesis Fall 2025 (DG1)/Code Implementation/Final/Results/Audit

Files:
- audit_decisions.csv
- common_columns.csv
- dataset_specific_columns.csv
- feature_group_summary.csv
- feature_summary_all.csv
- target_summary.csv

In [ ]:
# ================================================================
# SECTION 23: VERIFY AUDIT RESULTS
# ================================================================
#
# Purpose:
# Verify that all expected audit result files were successfully
# created and can be read back from disk.
# ================================================================

print("=" * 70)
print("AUDIT RESULTS VERIFICATION")
print("=" * 70)


# Expected output files
expected_audit_files = [
    "feature_summary_all.csv",
    "feature_group_summary.csv",
    "common_columns.csv",
    "dataset_specific_columns.csv",
    "target_summary.csv",
    "audit_decisions.csv"
]


verification_rows = []

for filename in expected_audit_files:

    file_path = AUDIT_RESULT_DIR / filename

    verification_rows.append({
        "File": filename,
        "Exists": file_path.exists(),
        "Size (KB)": round(
            file_path.stat().st_size / 1024, 2
        ) if file_path.exists() else 0
    })


verification_df = pd.DataFrame(
    verification_rows
)

display(verification_df)


# Check whether every expected file exists
all_files_exist = verification_df["Exists"].all()


print("\n" + "=" * 70)

if all_files_exist:
    print("AUDIT EXPORT STATUS: SUCCESS")
    print("All expected audit files are available.")
else:
    print("AUDIT EXPORT STATUS: WARNING")
    print("One or more expected audit files are missing.")

print("=" * 70)


# ----------------------------------------------------------------
# Optional read-back verification
# ----------------------------------------------------------------
# Read the saved files once to ensure they are valid CSV files.

if all_files_exist:

    feature_summary_check = pd.read_csv(
        AUDIT_RESULT_DIR / "feature_summary_all.csv"
    )

    group_summary_check = pd.read_csv(
        AUDIT_RESULT_DIR / "feature_group_summary.csv"
    )

    common_columns_check = pd.read_csv(
        AUDIT_RESULT_DIR / "common_columns.csv"
    )

    dataset_specific_check = pd.read_csv(
        AUDIT_RESULT_DIR / "dataset_specific_columns.csv"
    )

    target_summary_check = pd.read_csv(
        AUDIT_RESULT_DIR / "target_summary.csv"
    )

    audit_decisions_check = pd.read_csv(
        AUDIT_RESULT_DIR / "audit_decisions.csv"
    )

    print("\nRead-back verification completed successfully.")

    print("\nFile shapes:")
    print(
        "feature_summary_all:",
        feature_summary_check.shape
    )
    print(
        "feature_group_summary:",
        group_summary_check.shape
    )
    print(
        "common_columns:",
        common_columns_check.shape
    )
    print(
        "dataset_specific_columns:",
        dataset_specific_check.shape
    )
    print(
        "target_summary:",
        target_summary_check.shape
    )
    print(
        "audit_decisions:",
        audit_decisions_check.shape
    )

======================================================================
AUDIT RESULTS VERIFICATION
======================================================================

                           File  Exists  Size (KB)
0       feature_summary_all.csv    True      36.64
1     feature_group_summary.csv    True       1.53
2            common_columns.csv    True       0.94
3  dataset_specific_columns.csv    True       8.84
4            target_summary.csv    True       0.20
5           audit_decisions.csv    True       0.88

======================================================================
AUDIT EXPORT STATUS: SUCCESS
All expected audit files are available.
======================================================================

Read-back verification completed successfully.

File shapes:
feature_summary_all: (525, 7)
feature_group_summary: (36, 5)
common_columns: (70, 1)
dataset_specific_columns: (315, 2)
target_summary: (3, 7)
audit_decisions: (8, 4)